// Generated by scripts/generate_ess_registers.py; edit the JSON ledger.
#pragma once

#include <cstddef>
#include <stdint.h>
#include "RS485Motion/profiles/ess_rs/Types.h"

namespace RS485Motion { namespace ESS_RS {

/** Source addresses. HIGH/LOW suffixes are the manual's default-order labels.
 * Select the active word order before decoding paired fields. No I/O or setters. */
namespace Registers {
constexpr uint16_t DRIVER_MODEL = 0x0000;
constexpr uint16_t DRIVER_VERSION = 0x0001;
constexpr uint16_t ACTIVE_NODE = 0x0002;
constexpr uint16_t DIP_STATUS = 0x0003;
constexpr uint16_t ERROR_CODE = 0x0006;
constexpr uint16_t MOTION_STATUS = 0x0007;
constexpr uint16_t INPUT_STATUS = 0x0008;
constexpr uint16_t OUTPUT_STATUS = 0x0009;
constexpr uint16_t CURRENT_POSITION = 0x000A;
constexpr uint16_t CURRENT_POSITION_HIGH = 0x000A;
constexpr uint16_t CURRENT_POSITION_LOW = 0x000B;
constexpr uint16_t CURRENT_SPEED = 0x000C;
constexpr uint16_t DEFAULT_DIRECTION = 0x0010;
constexpr uint16_t SUBDIVISION = 0x0011;
constexpr uint16_t CUSTOM_NODE = 0x0013;
constexpr uint16_t BAUD_RATE = 0x0014;
constexpr uint16_t SERIAL_FORMAT = 0x0015;
constexpr uint16_t OVER_LIMIT_STOP = 0x0017;
constexpr uint16_t SOFT_LIMIT_ENABLE = 0x0018;
constexpr uint16_t WORD_ORDER = 0x0019;
constexpr uint16_t JOG_SPEED = 0x001D;
constexpr uint16_t JOG_ACCELERATION_TIME = 0x001E;
constexpr uint16_t JOG_DECELERATION_TIME = 0x001F;
constexpr uint16_t POSITION_START_SPEED = 0x0020;
constexpr uint16_t POSITION_ACCELERATION_TIME = 0x0021;
constexpr uint16_t POSITION_DECELERATION_TIME = 0x0022;
constexpr uint16_t POSITION_SPEED = 0x0023;
constexpr uint16_t POSITION_PULSES = 0x0024;
constexpr uint16_t POSITION_PULSES_HIGH = 0x0024;
constexpr uint16_t POSITION_PULSES_LOW = 0x0025;
constexpr uint16_t MOTION_COMMAND = 0x0027;
constexpr uint16_t AUXILIARY_COMMAND = 0x002D;
constexpr uint16_t HOMING_AUXILIARY = 0x0030;
constexpr uint16_t HOMING_METHOD = 0x0031;
constexpr uint16_t HOMING_SPEED = 0x0032;
constexpr uint16_t HOMING_QUERY_SPEED = 0x0033;
constexpr uint16_t HOMING_RAMP_TIME = 0x0034;
constexpr uint16_t HOMING_OFFSET = 0x0035;
constexpr uint16_t HOMING_OFFSET_HIGH = 0x0035;
constexpr uint16_t HOMING_OFFSET_LOW = 0x0036;
constexpr uint16_t POSITIVE_SOFT_LIMIT = 0x0037;
constexpr uint16_t POSITIVE_SOFT_LIMIT_HIGH = 0x0037;
constexpr uint16_t POSITIVE_SOFT_LIMIT_LOW = 0x0038;
constexpr uint16_t NEGATIVE_SOFT_LIMIT = 0x0039;
constexpr uint16_t NEGATIVE_SOFT_LIMIT_HIGH = 0x0039;
constexpr uint16_t NEGATIVE_SOFT_LIMIT_LOW = 0x003A;
constexpr uint16_t COLLISION_THRESHOLD_003B = 0x003B;
constexpr uint16_t COLLISION_CURRENT_003C = 0x003C;
constexpr uint16_t INPUT_POLARITY = 0x0040;
constexpr uint16_t INPUT_X0_FUNCTION = 0x0041;
constexpr uint16_t INPUT_X1_FUNCTION = 0x0042;
constexpr uint16_t INPUT_X2_FUNCTION = 0x0043;
constexpr uint16_t INPUT_X3_FUNCTION = 0x0044;
constexpr uint16_t OUTPUT_POLARITY = 0x004B;
constexpr uint16_t OUTPUT_Y0_FUNCTION = 0x004C;
constexpr uint16_t OUTPUT_Y1_FUNCTION = 0x004D;
constexpr uint16_t CUSTOM_OUTPUT = 0x004F;
constexpr uint16_t EXTERNAL_POSITION_MODE = 0x0050;
constexpr uint16_t PV_TRIGGER_MODE = 0x0051;
constexpr uint16_t POSITION_SEGMENT_01_PULSES = 0x0060;
constexpr uint16_t POSITION_SEGMENT_01_PULSES_HIGH = 0x0060;
constexpr uint16_t POSITION_SEGMENT_01_PULSES_LOW = 0x0061;
constexpr uint16_t POSITION_SEGMENT_01_SPEED = 0x0062;
constexpr uint16_t POSITION_SEGMENT_01_ACCELERATION_TIME = 0x0063;
constexpr uint16_t POSITION_SEGMENT_01_DECELERATION_TIME = 0x0064;
constexpr uint16_t POSITION_SEGMENT_01_RESERVED = 0x0065;
constexpr uint16_t POSITION_SEGMENT_02_PULSES = 0x0066;
constexpr uint16_t POSITION_SEGMENT_02_PULSES_HIGH = 0x0066;
constexpr uint16_t POSITION_SEGMENT_02_PULSES_LOW = 0x0067;
constexpr uint16_t POSITION_SEGMENT_02_SPEED = 0x0068;
constexpr uint16_t POSITION_SEGMENT_02_ACCELERATION_TIME = 0x0069;
constexpr uint16_t POSITION_SEGMENT_02_DECELERATION_TIME = 0x006A;
constexpr uint16_t POSITION_SEGMENT_02_RESERVED = 0x006B;
constexpr uint16_t POSITION_SEGMENT_03_PULSES = 0x006C;
constexpr uint16_t POSITION_SEGMENT_03_PULSES_HIGH = 0x006C;
constexpr uint16_t POSITION_SEGMENT_03_PULSES_LOW = 0x006D;
constexpr uint16_t POSITION_SEGMENT_03_SPEED = 0x006E;
constexpr uint16_t POSITION_SEGMENT_03_ACCELERATION_TIME = 0x006F;
constexpr uint16_t POSITION_SEGMENT_03_DECELERATION_TIME = 0x0070;
constexpr uint16_t POSITION_SEGMENT_03_RESERVED = 0x0071;
constexpr uint16_t POSITION_SEGMENT_04_PULSES = 0x0072;
constexpr uint16_t POSITION_SEGMENT_04_PULSES_HIGH = 0x0072;
constexpr uint16_t POSITION_SEGMENT_04_PULSES_LOW = 0x0073;
constexpr uint16_t POSITION_SEGMENT_04_SPEED = 0x0074;
constexpr uint16_t POSITION_SEGMENT_04_ACCELERATION_TIME = 0x0075;
constexpr uint16_t POSITION_SEGMENT_04_DECELERATION_TIME = 0x0076;
constexpr uint16_t POSITION_SEGMENT_04_RESERVED = 0x0077;
constexpr uint16_t POSITION_SEGMENT_05_PULSES = 0x0078;
constexpr uint16_t POSITION_SEGMENT_05_PULSES_HIGH = 0x0078;
constexpr uint16_t POSITION_SEGMENT_05_PULSES_LOW = 0x0079;
constexpr uint16_t POSITION_SEGMENT_05_SPEED = 0x007A;
constexpr uint16_t POSITION_SEGMENT_05_ACCELERATION_TIME = 0x007B;
constexpr uint16_t POSITION_SEGMENT_05_DECELERATION_TIME = 0x007C;
constexpr uint16_t POSITION_SEGMENT_05_RESERVED = 0x007D;
constexpr uint16_t POSITION_SEGMENT_06_PULSES = 0x007E;
constexpr uint16_t POSITION_SEGMENT_06_PULSES_HIGH = 0x007E;
constexpr uint16_t POSITION_SEGMENT_06_PULSES_LOW = 0x007F;
constexpr uint16_t POSITION_SEGMENT_06_SPEED = 0x0080;
constexpr uint16_t POSITION_SEGMENT_06_ACCELERATION_TIME = 0x0081;
constexpr uint16_t POSITION_SEGMENT_06_DECELERATION_TIME = 0x0082;
constexpr uint16_t POSITION_SEGMENT_06_RESERVED = 0x0083;
constexpr uint16_t POSITION_SEGMENT_07_PULSES = 0x0084;
constexpr uint16_t POSITION_SEGMENT_07_PULSES_HIGH = 0x0084;
constexpr uint16_t POSITION_SEGMENT_07_PULSES_LOW = 0x0085;
constexpr uint16_t POSITION_SEGMENT_07_SPEED = 0x0086;
constexpr uint16_t POSITION_SEGMENT_07_ACCELERATION_TIME = 0x0087;
constexpr uint16_t POSITION_SEGMENT_07_DECELERATION_TIME = 0x0088;
constexpr uint16_t POSITION_SEGMENT_07_RESERVED = 0x0089;
constexpr uint16_t POSITION_SEGMENT_08_PULSES = 0x008A;
constexpr uint16_t POSITION_SEGMENT_08_PULSES_HIGH = 0x008A;
constexpr uint16_t POSITION_SEGMENT_08_PULSES_LOW = 0x008B;
constexpr uint16_t POSITION_SEGMENT_08_SPEED = 0x008C;
constexpr uint16_t POSITION_SEGMENT_08_ACCELERATION_TIME = 0x008D;
constexpr uint16_t POSITION_SEGMENT_08_DECELERATION_TIME = 0x008E;
constexpr uint16_t POSITION_SEGMENT_08_RESERVED = 0x008F;
constexpr uint16_t POSITION_SEGMENT_09_PULSES = 0x0090;
constexpr uint16_t POSITION_SEGMENT_09_PULSES_HIGH = 0x0090;
constexpr uint16_t POSITION_SEGMENT_09_PULSES_LOW = 0x0091;
constexpr uint16_t POSITION_SEGMENT_09_SPEED = 0x0092;
constexpr uint16_t POSITION_SEGMENT_09_ACCELERATION_TIME = 0x0093;
constexpr uint16_t POSITION_SEGMENT_09_DECELERATION_TIME = 0x0094;
constexpr uint16_t POSITION_SEGMENT_09_RESERVED = 0x0095;
constexpr uint16_t POSITION_SEGMENT_10_PULSES = 0x0096;
constexpr uint16_t POSITION_SEGMENT_10_PULSES_HIGH = 0x0096;
constexpr uint16_t POSITION_SEGMENT_10_PULSES_LOW = 0x0097;
constexpr uint16_t POSITION_SEGMENT_10_SPEED = 0x0098;
constexpr uint16_t POSITION_SEGMENT_10_ACCELERATION_TIME = 0x0099;
constexpr uint16_t POSITION_SEGMENT_10_DECELERATION_TIME = 0x009A;
constexpr uint16_t POSITION_SEGMENT_10_RESERVED = 0x009B;
constexpr uint16_t POSITION_SEGMENT_11_PULSES = 0x009C;
constexpr uint16_t POSITION_SEGMENT_11_PULSES_HIGH = 0x009C;
constexpr uint16_t POSITION_SEGMENT_11_PULSES_LOW = 0x009D;
constexpr uint16_t POSITION_SEGMENT_11_SPEED = 0x009E;
constexpr uint16_t POSITION_SEGMENT_11_ACCELERATION_TIME = 0x009F;
constexpr uint16_t POSITION_SEGMENT_11_DECELERATION_TIME = 0x00A0;
constexpr uint16_t POSITION_SEGMENT_11_RESERVED = 0x00A1;
constexpr uint16_t POSITION_SEGMENT_12_PULSES = 0x00A2;
constexpr uint16_t POSITION_SEGMENT_12_PULSES_HIGH = 0x00A2;
constexpr uint16_t POSITION_SEGMENT_12_PULSES_LOW = 0x00A3;
constexpr uint16_t POSITION_SEGMENT_12_SPEED = 0x00A4;
constexpr uint16_t POSITION_SEGMENT_12_ACCELERATION_TIME = 0x00A5;
constexpr uint16_t POSITION_SEGMENT_12_DECELERATION_TIME = 0x00A6;
constexpr uint16_t POSITION_SEGMENT_12_RESERVED = 0x00A7;
constexpr uint16_t POSITION_SEGMENT_13_PULSES = 0x00A8;
constexpr uint16_t POSITION_SEGMENT_13_PULSES_HIGH = 0x00A8;
constexpr uint16_t POSITION_SEGMENT_13_PULSES_LOW = 0x00A9;
constexpr uint16_t POSITION_SEGMENT_13_SPEED = 0x00AA;
constexpr uint16_t POSITION_SEGMENT_13_ACCELERATION_TIME = 0x00AB;
constexpr uint16_t POSITION_SEGMENT_13_DECELERATION_TIME = 0x00AC;
constexpr uint16_t POSITION_SEGMENT_13_RESERVED = 0x00AD;
constexpr uint16_t POSITION_SEGMENT_14_PULSES = 0x00AE;
constexpr uint16_t POSITION_SEGMENT_14_PULSES_HIGH = 0x00AE;
constexpr uint16_t POSITION_SEGMENT_14_PULSES_LOW = 0x00AF;
constexpr uint16_t POSITION_SEGMENT_14_SPEED = 0x00B0;
constexpr uint16_t POSITION_SEGMENT_14_ACCELERATION_TIME = 0x00B1;
constexpr uint16_t POSITION_SEGMENT_14_DECELERATION_TIME = 0x00B2;
constexpr uint16_t POSITION_SEGMENT_14_RESERVED = 0x00B3;
constexpr uint16_t POSITION_SEGMENT_15_PULSES = 0x00B4;
constexpr uint16_t POSITION_SEGMENT_15_PULSES_HIGH = 0x00B4;
constexpr uint16_t POSITION_SEGMENT_15_PULSES_LOW = 0x00B5;
constexpr uint16_t POSITION_SEGMENT_15_SPEED = 0x00B6;
constexpr uint16_t POSITION_SEGMENT_15_ACCELERATION_TIME = 0x00B7;
constexpr uint16_t POSITION_SEGMENT_15_DECELERATION_TIME = 0x00B8;
constexpr uint16_t POSITION_SEGMENT_15_RESERVED = 0x00B9;
constexpr uint16_t POSITION_SEGMENT_16_PULSES = 0x00BA;
constexpr uint16_t POSITION_SEGMENT_16_PULSES_HIGH = 0x00BA;
constexpr uint16_t POSITION_SEGMENT_16_PULSES_LOW = 0x00BB;
constexpr uint16_t POSITION_SEGMENT_16_SPEED = 0x00BC;
constexpr uint16_t POSITION_SEGMENT_16_ACCELERATION_TIME = 0x00BD;
constexpr uint16_t POSITION_SEGMENT_16_DECELERATION_TIME = 0x00BE;
constexpr uint16_t POSITION_SEGMENT_16_RESERVED = 0x00BF;
constexpr uint16_t SPEED_SEGMENT_01_SPEED = 0x00C0;
constexpr uint16_t SPEED_SEGMENT_01_ACCELERATION_TIME = 0x00C1;
constexpr uint16_t SPEED_SEGMENT_01_DECELERATION_TIME = 0x00C2;
constexpr uint16_t SPEED_SEGMENT_02_SPEED = 0x00C3;
constexpr uint16_t SPEED_SEGMENT_02_ACCELERATION_TIME = 0x00C4;
constexpr uint16_t SPEED_SEGMENT_02_DECELERATION_TIME = 0x00C5;
constexpr uint16_t SPEED_SEGMENT_03_SPEED = 0x00C6;
constexpr uint16_t SPEED_SEGMENT_03_ACCELERATION_TIME = 0x00C7;
constexpr uint16_t SPEED_SEGMENT_03_DECELERATION_TIME = 0x00C8;
constexpr uint16_t SPEED_SEGMENT_04_SPEED = 0x00C9;
constexpr uint16_t SPEED_SEGMENT_04_ACCELERATION_TIME = 0x00CA;
constexpr uint16_t SPEED_SEGMENT_04_DECELERATION_TIME = 0x00CB;
constexpr uint16_t SPEED_SEGMENT_05_SPEED = 0x00CC;
constexpr uint16_t SPEED_SEGMENT_05_ACCELERATION_TIME = 0x00CD;
constexpr uint16_t SPEED_SEGMENT_05_DECELERATION_TIME = 0x00CE;
constexpr uint16_t SPEED_SEGMENT_06_SPEED = 0x00CF;
constexpr uint16_t SPEED_SEGMENT_06_ACCELERATION_TIME = 0x00D0;
constexpr uint16_t SPEED_SEGMENT_06_DECELERATION_TIME = 0x00D1;
constexpr uint16_t SPEED_SEGMENT_07_SPEED = 0x00D2;
constexpr uint16_t SPEED_SEGMENT_07_ACCELERATION_TIME = 0x00D3;
constexpr uint16_t SPEED_SEGMENT_07_DECELERATION_TIME = 0x00D4;
constexpr uint16_t SPEED_SEGMENT_08_SPEED = 0x00D5;
constexpr uint16_t SPEED_SEGMENT_08_ACCELERATION_TIME = 0x00D6;
constexpr uint16_t SPEED_SEGMENT_08_DECELERATION_TIME = 0x00D7;
constexpr uint16_t SPEED_SEGMENT_09_SPEED = 0x00D8;
constexpr uint16_t SPEED_SEGMENT_09_ACCELERATION_TIME = 0x00D9;
constexpr uint16_t SPEED_SEGMENT_09_DECELERATION_TIME = 0x00DA;
constexpr uint16_t SPEED_SEGMENT_10_SPEED = 0x00DB;
constexpr uint16_t SPEED_SEGMENT_10_ACCELERATION_TIME = 0x00DC;
constexpr uint16_t SPEED_SEGMENT_10_DECELERATION_TIME = 0x00DD;
constexpr uint16_t SPEED_SEGMENT_11_SPEED = 0x00DE;
constexpr uint16_t SPEED_SEGMENT_11_ACCELERATION_TIME = 0x00DF;
constexpr uint16_t SPEED_SEGMENT_11_DECELERATION_TIME = 0x00E0;
constexpr uint16_t SPEED_SEGMENT_12_SPEED = 0x00E1;
constexpr uint16_t SPEED_SEGMENT_12_ACCELERATION_TIME = 0x00E2;
constexpr uint16_t SPEED_SEGMENT_12_DECELERATION_TIME = 0x00E3;
constexpr uint16_t SPEED_SEGMENT_13_SPEED = 0x00E4;
constexpr uint16_t SPEED_SEGMENT_13_ACCELERATION_TIME = 0x00E5;
constexpr uint16_t SPEED_SEGMENT_13_DECELERATION_TIME = 0x00E6;
constexpr uint16_t SPEED_SEGMENT_14_SPEED = 0x00E7;
constexpr uint16_t SPEED_SEGMENT_14_ACCELERATION_TIME = 0x00E8;
constexpr uint16_t SPEED_SEGMENT_14_DECELERATION_TIME = 0x00E9;
constexpr uint16_t SPEED_SEGMENT_15_SPEED = 0x00EA;
constexpr uint16_t SPEED_SEGMENT_15_ACCELERATION_TIME = 0x00EB;
constexpr uint16_t SPEED_SEGMENT_15_DECELERATION_TIME = 0x00EC;
constexpr uint16_t SPEED_SEGMENT_16_SPEED = 0x00ED;
constexpr uint16_t SPEED_SEGMENT_16_ACCELERATION_TIME = 0x00EE;
constexpr uint16_t SPEED_SEGMENT_16_DECELERATION_TIME = 0x00EF;
constexpr uint16_t CONTROL_ALGORITHM = 0x0100;
constexpr uint16_t ENCODER_RESOLUTION = 0x0101;
constexpr uint16_t MAXIMUM_CURRENT = 0x0102;
constexpr uint16_t CLOSED_LOOP_CURRENT_PERCENT = 0x0103;
constexpr uint16_t BASE_CURRENT_PERCENT = 0x0104;
constexpr uint16_t OPEN_LOOP_CURRENT_PERCENT = 0x0105;
constexpr uint16_t LOCK_CURRENT_PERCENT = 0x0106;
constexpr uint16_t LOCK_TIME = 0x0107;
constexpr uint16_t INPUT_FILTER = 0x0108;
constexpr uint16_t PULSE_LOW_PASS_FILTER = 0x0109;
constexpr uint16_t POSITION_ERROR_ALARM_THRESHOLD = 0x010A;
constexpr uint16_t POSITION_ARRIVAL_WINDOW = 0x010B;
constexpr uint16_t ARRIVAL_TIME = 0x010C;
constexpr uint16_t PULSE_MEAN_FILTER = 0x010D;
constexpr uint16_t CURRENT_LOOP_KP_MULTIPLIER = 0x010E;
constexpr uint16_t CURRENT_LOOP_KP = 0x010F;
constexpr uint16_t CURRENT_LOOP_KI = 0x0110;
constexpr uint16_t CURRENT_LOOP_KC = 0x0111;
constexpr uint16_t LA_SPEED_KP1 = 0x0112;
constexpr uint16_t LA_SPEED_KV1 = 0x0113;
constexpr uint16_t LA_SPEED_NODE1 = 0x0114;
constexpr uint16_t LA_SPEED_KP2 = 0x0115;
constexpr uint16_t LA_SPEED_KV2 = 0x0116;
constexpr uint16_t LA_SPEED_NODE2 = 0x0117;
constexpr uint16_t LA_SPEED_FEEDFORWARD_KVF = 0x0118;
constexpr uint16_t LA_POSITION_KI = 0x0119;
constexpr uint16_t COLLISION_THRESHOLD_0122 = 0x0122;
constexpr uint16_t COLLISION_CURRENT_0123 = 0x0123;
constexpr uint16_t SEGMENT_START_SPEED_01_VALUE = 0x0130;
constexpr uint16_t SEGMENT_START_SPEED_02_VALUE = 0x0131;
constexpr uint16_t SEGMENT_START_SPEED_03_VALUE = 0x0132;
constexpr uint16_t SEGMENT_START_SPEED_04_VALUE = 0x0133;
constexpr uint16_t SEGMENT_START_SPEED_05_VALUE = 0x0134;
constexpr uint16_t SEGMENT_START_SPEED_06_VALUE = 0x0135;
constexpr uint16_t SEGMENT_START_SPEED_07_VALUE = 0x0136;
constexpr uint16_t SEGMENT_START_SPEED_08_VALUE = 0x0137;
constexpr uint16_t SEGMENT_START_SPEED_09_VALUE = 0x0138;
constexpr uint16_t SEGMENT_START_SPEED_10_VALUE = 0x0139;
constexpr uint16_t SEGMENT_START_SPEED_11_VALUE = 0x013A;
constexpr uint16_t SEGMENT_START_SPEED_12_VALUE = 0x013B;
constexpr uint16_t SEGMENT_START_SPEED_13_VALUE = 0x013C;
constexpr uint16_t SEGMENT_START_SPEED_14_VALUE = 0x013D;
constexpr uint16_t SEGMENT_START_SPEED_15_VALUE = 0x013E;
constexpr uint16_t SEGMENT_START_SPEED_16_VALUE = 0x013F;
} // namespace Registers

/** Immutable catalogue metadata, not an operational read/write capability.
 * All strings have static lifetime. Ranges/defaults are source text, never
 * executable validation or initialization values. Every word is 16 bits.
 * sourceAccess retains RW/S without claiming persistence semantics.
 * No field or entry is hardware-qualified by this catalogue. */
struct RegisterDescriptor {
    uint16_t address;
    uint8_t wordCount;
    RegisterAccess access;
    RegisterSignedness signedness;
    RegisterWordOrder wordOrder;
    uint32_t issues;
    uint8_t sourcePage;
    const char* name;
    const char* unit;
    const char* sourceRange;
    const char* sourceDefault;
    const char* sourceAccess;
    const char* notes;
};

/** Semantic homing choice; method is not a negative wire encoding. */
struct HomingMethodDescriptor {
    int16_t method;
    uint8_t firstSourcePage;
    bool requiresMotorIndex;
    bool semanticsUnresolved;
    const char* notes;
};

/** Return the fixed descriptor count; no allocation, state mutation or I/O. */
std::size_t registerCount() noexcept;
/** Return immutable entry for zero-based index, or nullptr when out of range. */
const RegisterDescriptor* registerAt(std::size_t index) noexcept;
/** Return the entry containing address, including the second word of a pair.
 * Unknown holes/outside-map addresses return nullptr. Reserved entries remain
 * visible with access RESERVED. Bounded search; returned pointer is static. */
const RegisterDescriptor* findRegister(uint16_t address) noexcept;
/** Source issue test only; this does not establish an operation's support. */
bool hasRegisterIssue(const RegisterDescriptor& entry, RegisterIssue issue) noexcept;
/** Position segment 1..16; invalid segment/field returns nullptr. No I/O. */
const RegisterDescriptor* positionSegmentRegister(uint8_t segment, PositionSegmentField field) noexcept;
/** Speed segment 1..16; invalid segment/field returns nullptr. No I/O. */
const RegisterDescriptor* speedSegmentRegister(uint8_t segment, SpeedSegmentField field) noexcept;
/** Shared PT/PV starting-speed segment 1..16; invalid index returns nullptr. */
const RegisterDescriptor* segmentStartSpeedRegister(uint8_t segment) noexcept;
/** X terminal 0..3; invalid terminal returns nullptr. */
const RegisterDescriptor* inputFunctionRegister(uint8_t terminal) noexcept;
/** Y terminal 0..1; invalid terminal returns nullptr. */
const RegisterDescriptor* outputFunctionRegister(uint8_t terminal) noexcept;
/** Fixed count of listed semantic homing choices, including unresolved negatives. */
std::size_t homingMethodCount() noexcept;
/** Listed choice or nullptr; lookup is not approval to encode or execute it. */
const HomingMethodDescriptor* findHomingMethod(int16_t method) noexcept;

}} // namespace RS485Motion::ESS_RS
