// Generated by scripts/generate_ess_registers.py; edit the JSON ledger.
#pragma once

#include <stdint.h>

namespace MotorControlRS { namespace ESS_RS {

/** Source access only; it is not authorization to perform a transaction. */
enum class RegisterAccess : uint8_t { READ_ONLY, WRITE_ONLY, READ_WRITE, UNSPECIFIED, RESERVED };
/** Signed semantic values are distinguished from an established wire encoding. */
enum class RegisterSignedness : uint8_t { UNSIGNED, SIGNED_ENCODING_UNRESOLVED, BITFIELD, ENUMERATED, UNRESOLVED, RESERVED };
/** CONFIGURABLE requires an explicit active WordOrder; it never supplies a default. */
enum class RegisterWordOrder : uint8_t { SINGLE_REGISTER, CONFIGURABLE, UNRESOLVED };
/** Per-entry source issues; these flags are independent of hardware qualification. */
enum class RegisterIssue : uint32_t {
    NONE = 0,
    DEFAULT_CONFLICT = 0x00000001u,
    RANGE_MALFORMED = 0x00000002u,
    SCALE_UNRESOLVED = 0x00000004u,
    SIGNED_ENCODING_UNRESOLVED = 0x00000008u,
    ACCESS_UNSPECIFIED = 0x00000010u,
    DUPLICATE_MAPPING = 0x00000020u,
    MODEL_APPLICABILITY = 0x00000040u,
    WORD_ORDER_UNRESOLVED = 0x00000080u,
    SOURCE_CONFLICT = 0x00000100u,
    UNIT_UNSPECIFIED = 0x00000200u,
    SEMANTICS_UNRESOLVED = 0x00000400u,
};

/** Does not change Modbus byte order within a 16-bit register. Source function-PDF pages: 30, 70. */
enum class WordOrder : uint16_t {
    /** Lower address stores high 16 bits. */
    HIGH_WORD_FIRST = 0,
    /** Lower address stores low 16 bits. */
    LOW_WORD_FIRST = 1,
};

/** DefaultDirection Source function-PDF pages: 69. */
enum class DefaultDirection : uint16_t {
    /** Default movement direction. */
    NORMAL = 0,
    /** Reverse default movement direction. */
    REVERSED = 1,
};

/** BaudRateCode Source function-PDF pages: 69. */
enum class BaudRateCode : uint16_t {
    /** 115200 baud; power cycle required after changing. */
    BAUD_115200 = 0,
    /** 38400 baud; power cycle required after changing. */
    BAUD_38400 = 1,
    /** 19200 baud; power cycle required after changing. */
    BAUD_19200 = 2,
    /** 9600 baud; power cycle required after changing. */
    BAUD_9600 = 3,
};

/** SerialFormatCode Source function-PDF pages: 69. */
enum class SerialFormatCode : uint16_t {
    /** 8N1; power cycle required after changing. */
    FORMAT_8N1 = 0,
    /** 8N2; power cycle required after changing. */
    FORMAT_8N2 = 1,
    /** 8E1; power cycle required after changing. */
    FORMAT_8E1 = 2,
    /** 8O1; power cycle required after changing. */
    FORMAT_8O1 = 3,
};

/** OverLimitStop Source function-PDF pages: 70. */
enum class OverLimitStop : uint16_t {
    /** Source term; stopping/torque semantics unresolved. */
    FREE_PARKING = 0,
    /** Emergency stop selection. */
    EMERGENCY_STOP = 1,
};

/** SoftLimitEnable Source function-PDF pages: 29, 70. */
enum class SoftLimitEnable : uint16_t {
    /** Software limits disabled. */
    LIMITS_OFF = 0,
    /** Limits effective only after returning to zero. */
    AFTER_HOMING = 1,
};

/** Used for external position mode register; motion-command bit 2 is a separate mask. Source function-PDF pages: 16, 75. */
enum class PositionMode : uint16_t {
    /** Relative target. */
    RELATIVE = 0,
    /** Absolute target. */
    ABSOLUTE = 1,
};

/** PvTriggerMode Source function-PDF pages: 29, 75. */
enum class PvTriggerMode : uint16_t {
    /** Active level trigger. */
    LEVEL = 0,
    /** Rising-edge trigger; needed for mixed PT/PV fixed-length operation. */
    RISING_EDGE = 1,
};

/** ControlAlgorithm Source function-PDF pages: 77. */
enum class ControlAlgorithm : uint16_t {
    /** Open-loop operation. */
    OPEN_LOOP = 1,
    /** Closed-loop algorithm 1 per source. */
    ALGORITHM_1 = 2,
};

/** Bit masks only; combinations and physical completion are not validated. Unnamed bits remain unknown. Source function-PDF pages: 13, 14, 16, 18, 19, 25, 70, 71. */
enum class MotionCommandBit : uint16_t {
    /** Generate position start. */
    START_POSITION = 1,
    /** Generate serial speed start. */
    START_SPEED = 2,
    /** 1: absolute; 0: relative. */
    ABSOLUTE_POSITION = 4,
    /** 1: interrupt current positioning; 0: ignore new positioning command while busy. Valid only positioning per p16. */
    INTERRUPT_POSITION = 8,
    /** Generate homing start. */
    START_HOMING = 16,
    /** Decelerate with preconfigured ramp. */
    STOP = 256,
    /** Source says direct stop without deceleration. */
    EMERGENCY_STOP = 512,
};

/** AuxiliaryCommand Source function-PDF pages: 26, 71. */
enum class AuxiliaryCommand : uint16_t {
    /** No valid action. */
    INVALID = 0,
    /** Release motor. */
    RELEASE = 17,
    /** Enable motor. */
    ENABLE = 18,
    /** Clear a resettable alarm. */
    CLEAR_ALARM = 33,
    /** Clear current motor position. */
    CLEAR_POSITION = 49,
    /** Restore factory parameters; ignored unless stopped. */
    RESTORE_FACTORY = 65,
    /** Save all parameters; ignored unless stopped. */
    SAVE_PARAMETERS = 66,
};

/** Bits 7-15 are undocumented, not normalized to false. Source function-PDF pages: 68. */
enum class MotionStatusBit : uint16_t {
    /** 1: in position; 0: not in position. */
    IN_POSITION = 1,
    /** 1: homing complete; 0: not complete. */
    HOMING_COMPLETE = 2,
    /** 1: running; 0: stationary. */
    RUNNING = 4,
    /** 1: alarm; 0: normal. */
    ALARM = 8,
    /** 1: released; 0: enabled; source label Motor enable bit has inverted polarity. */
    RELEASED = 16,
    /** 1: positive limit overtravel flag valid. */
    POSITIVE_SOFT_LIMIT = 32,
    /** 1: negative limit overtravel flag valid. */
    NEGATIVE_SOFT_LIMIT = 64,
};

/** Bits 4-15 are reserved in corresponding ESS registers. Source function-PDF pages: 68, 69, 73. */
enum class InputBit : uint16_t {
    /** Input X0; bit semantics depend on status versus polarity register. */
    X0 = 1,
    /** Input X1; bit semantics depend on status versus polarity register. */
    X1 = 2,
    /** Input X2; bit semantics depend on status versus polarity register. */
    X2 = 4,
    /** Input X3; bit semantics depend on status versus polarity register. */
    X3 = 8,
};

/** Bits 2-15 are reserved in corresponding ESS registers. Source function-PDF pages: 69, 74. */
enum class OutputBit : uint16_t {
    /** Output Y0; bit semantics depend on status, polarity or custom-output register. */
    Y0 = 1,
    /** Output Y1; bit semantics depend on status, polarity or custom-output register. */
    Y1 = 2,
};

/** The function manual lists 7 switches; ESS23 hardware p8 defines 5. These names record source labels, not confirmed board mapping. Source function-PDF pages: 68. */
enum class DipStatusBit : uint16_t {
    /** Source labels bit 0 as SW1; hardware mapping unqualified. */
    SOURCE_SW1 = 1,
    /** Source labels bit 1 as SW2; hardware mapping unqualified. */
    SOURCE_SW2 = 2,
    /** Source labels bit 2 as SW3; hardware mapping unqualified. */
    SOURCE_SW3 = 4,
    /** Source labels bit 3 as SW4; hardware mapping unqualified. */
    SOURCE_SW4 = 8,
    /** Source labels bit 4 as SW5; hardware mapping unqualified. */
    SOURCE_SW5 = 16,
    /** Source labels bit 5 as SW6; hardware mapping unqualified. */
    SOURCE_SW6 = 32,
    /** Source labels bit 6 as SW7; hardware mapping unqualified. */
    SOURCE_SW7 = 64,
};

/** InputFunction Source function-PDF pages: 14, 18, 19, 22, 23, 24, 27, 73, 74. */
enum class InputFunction : uint16_t {
    /** No function. */
    UNDEFINED = 0,
    /** Origin sensor. */
    ORIGIN = 1,
    /** Positive-limit sensor. */
    POSITIVE_LIMIT = 2,
    /** Negative-limit sensor. */
    NEGATIVE_LIMIT = 3,
    /** Valid level releases motor. */
    RELEASE_MOTOR = 4,
    /** Valid level forces stop. */
    STOP = 5,
    /** Valid level forces urgent stop. */
    EMERGENCY_STOP = 6,
    /** Position start; edge valid. */
    POSITION_MOVE = 7,
    /** Speed mode; level valid; speed sign sets direction. */
    SPEED_MOVE = 8,
    /** Level-valid motion always positive regardless speed sign. */
    JOG_POSITIVE = 9,
    /** Level-valid motion always negative regardless speed sign. */
    JOG_NEGATIVE = 10,
    /** Homing start; edge valid. */
    START_HOMING = 11,
    /** Position-segment trigger; edge valid. */
    PT_TRIGGER = 12,
    /** Speed-segment trigger; level or configured rising edge. */
    PV_TRIGGER = 13,
    /** Least significant segment selector. */
    SEGMENT_PIN0 = 14,
    /** Segment selector bit 1. */
    SEGMENT_PIN1 = 15,
    /** Segment selector bit 2. */
    SEGMENT_PIN2 = 16,
    /** Most significant segment selector. */
    SEGMENT_PIN3 = 17,
};

/** Values 6-8 lack descriptions and are deliberately not enum members. Source function-PDF pages: 28, 74. */
enum class OutputFunction : uint16_t {
    /** No function. */
    UNDEFINED = 0,
    /** Valid level when alarm. */
    ALARM = 1,
    /** Valid level when drive moves. */
    RUNNING = 2,
    /** Valid level after homing. */
    HOMING_COMPLETE = 3,
    /** Valid level when correct position reached. */
    IN_POSITION = 4,
    /** Valid when motor locked; invalid when released. */
    BRAKE = 5,
    /** Custom output controlled through 0x004F. */
    CUSTOM_0 = 9,
    /** Custom output controlled through 0x004F. */
    CUSTOM_1 = 10,
    /** Listed choice; mapping to only two ESS outputs unresolved. */
    CUSTOM_2 = 11,
};

/** HomingAuxiliary Source function-PDF pages: 72. */
enum class HomingAuxiliary : uint16_t {
    /** Run offset; resulting coordinate is offset value. */
    MOVE_OFFSET_SET_OFFSET = 0,
    /** Run offset; resulting coordinate is zero. */
    MOVE_OFFSET_SET_ZERO = 1,
    /** Run offset; resulting coordinate is negative offset value. */
    MOVE_OFFSET_SET_NEGATIVE_OFFSET = 2,
    /** Run offset; resulting coordinate is actual value. */
    MOVE_OFFSET_KEEP_ACTUAL = 3,
    /** Run offset; resulting coordinate is actual value plus offset. */
    MOVE_OFFSET_ADD_OFFSET = 4,
    /** Run offset; resulting coordinate is actual value minus offset. */
    MOVE_OFFSET_SUBTRACT_OFFSET = 5,
    /** Do not run offset; resulting coordinate is offset value. */
    KEEP_POSITION_SET_OFFSET = 6,
    /** Do not run offset; resulting coordinate is zero. */
    KEEP_POSITION_SET_ZERO = 7,
    /** Do not run offset; resulting coordinate is negative offset value. */
    KEEP_POSITION_SET_NEGATIVE_OFFSET = 8,
    /** Do not run offset; resulting coordinate is actual value. */
    KEEP_POSITION_KEEP_ACTUAL = 9,
    /** Do not run offset; resulting coordinate is actual value plus offset. */
    KEEP_POSITION_ADD_OFFSET = 10,
    /** Do not run offset; resulting coordinate is actual value minus offset. */
    KEEP_POSITION_SUBTRACT_OFFSET = 11,
};

/** Semantic method numbers, NOT a negative-value wire encoder. Modes 1-14, 33, 34 require closed-loop motor Z index. Modes 15, 16, 31, 32, 0 are not listed. Source function-PDF pages: 19, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 72, 73. */
enum class HomingMethod : int16_t {
    /** Collision mode listed in ESS table; trajectory and negative wire encoding unresolved. */
    COLLISION_MINUS_4 = -4,
    /** Collision mode listed in ESS table; trajectory and negative wire encoding unresolved. */
    COLLISION_MINUS_3 = -3,
    /** Collision mode listed in ESS table; trajectory and negative wire encoding unresolved. */
    COLLISION_MINUS_2 = -2,
    /** Collision mode listed in ESS table; trajectory and negative wire encoding unresolved. */
    COLLISION_MINUS_1 = -1,
    /** Method 1: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_1 = 1,
    /** Method 2: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_2 = 2,
    /** Method 3: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_3 = 3,
    /** Method 4: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_4 = 4,
    /** Method 5: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_5 = 5,
    /** Method 6: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_6 = 6,
    /** Method 7: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_7 = 7,
    /** Method 8: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_8 = 8,
    /** Method 9: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_9 = 9,
    /** Method 10: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_10 = 10,
    /** Method 11: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_11 = 11,
    /** Method 12: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_12 = 12,
    /** Method 13: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_13 = 13,
    /** Method 14: reference motor Z index; use cited diagrams for starting-state-dependent paths. */
    METHOD_14 = 14,
    /** Method 17: reference negative limit; use cited diagrams for starting-state-dependent paths. */
    METHOD_17 = 17,
    /** Method 18: reference positive limit; use cited diagrams for starting-state-dependent paths. Figure labels negative limit conflict with positive-limit prose; retain discrepancy. */
    METHOD_18 = 18,
    /** Method 19: reference origin input; use cited diagrams for starting-state-dependent paths. */
    METHOD_19 = 19,
    /** Method 20: reference origin input; use cited diagrams for starting-state-dependent paths. */
    METHOD_20 = 20,
    /** Method 21: reference origin input; use cited diagrams for starting-state-dependent paths. */
    METHOD_21 = 21,
    /** Method 22: reference origin input; use cited diagrams for starting-state-dependent paths. */
    METHOD_22 = 22,
    /** Method 23: reference origin input; use cited diagrams for starting-state-dependent paths. */
    METHOD_23 = 23,
    /** Method 24: reference origin input; use cited diagrams for starting-state-dependent paths. */
    METHOD_24 = 24,
    /** Method 25: reference origin input; use cited diagrams for starting-state-dependent paths. */
    METHOD_25 = 25,
    /** Method 26: reference origin input; use cited diagrams for starting-state-dependent paths. */
    METHOD_26 = 26,
    /** Method 27: reference origin input; use cited diagrams for starting-state-dependent paths. */
    METHOD_27 = 27,
    /** Method 28: reference origin input; use cited diagrams for starting-state-dependent paths. */
    METHOD_28 = 28,
    /** Method 29: reference origin input; use cited diagrams for starting-state-dependent paths. */
    METHOD_29 = 29,
    /** Method 30: reference origin input; use cited diagrams for starting-state-dependent paths. */
    METHOD_30 = 30,
    /** Method 33: negative low-speed search for motor Z index; no slowdown input. */
    METHOD_33 = 33,
    /** Method 34: positive low-speed search for motor Z index; no slowdown input. */
    METHOD_34 = 34,
    /** Method 35: source says set current position as origin; not a sensor-search motion. */
    METHOD_35 = 35,
};

/** Labels for 1, 2, 3, 5 additionally from hardware manual p12; no label invented for 4. Unknown values must be retained. Source function-PDF pages: 68. */
enum class AlarmCode : uint16_t {
    /** Function manual p68 normal. */
    NORMAL = 0,
    /** Hardware p12 phase overcurrent or short; re-power reset. */
    OVERCURRENT = 1,
    /** Hardware p12 supply voltage high; automatic reset. */
    OVERVOLTAGE = 2,
    /** Hardware p12 supply voltage low; automatic reset. */
    UNDERVOLTAGE = 3,
    /** Hardware p12 out of tolerance; re-power reset. */
    POSITION_TOLERANCE = 5,
};

/** Offsets within one documented position segment; index is 1 through 16. */
enum class PositionSegmentField : uint8_t { PULSES = 0, SPEED = 2, ACCELERATION_TIME = 3, DECELERATION_TIME = 4, RESERVED = 5 };
/** Offsets within one documented speed segment; index is 1 through 16. */
enum class SpeedSegmentField : uint8_t { SPEED = 0, ACCELERATION_TIME = 1, DECELERATION_TIME = 2 };

}} // namespace MotorControlRS::ESS_RS
