// Generated by scripts/generate_ess_registers.py; edit the JSON ledger.
#pragma once

#include <stdint.h>

namespace MotorControlRS { namespace ESS_RS {
namespace Detail {
// bit0: readable; bit1: single-word writable. Zero rejects raw access.
constexpr uint8_t ACCESS[] = {
    1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, // 0x0000
    3, 3, 0, 3, 3, 3, 0, 3, 3, 3, 0, 0, 0, 3, 3, 3, // 0x0010
    3, 3, 3, 3, 1, 1, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, // 0x0020
    3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, // 0x0030
    3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 3, // 0x0040
    3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 0x0050
    1, 1, 3, 3, 3, 0, 1, 1, 3, 3, 3, 0, 1, 1, 3, 3, // 0x0060
    3, 0, 1, 1, 3, 3, 3, 0, 1, 1, 3, 3, 3, 0, 1, 1, // 0x0070
    3, 3, 3, 0, 1, 1, 3, 3, 3, 0, 1, 1, 3, 3, 3, 0, // 0x0080
    1, 1, 3, 3, 3, 0, 1, 1, 3, 3, 3, 0, 1, 1, 3, 3, // 0x0090
    3, 0, 1, 1, 3, 3, 3, 0, 1, 1, 3, 3, 3, 0, 1, 1, // 0x00A0
    3, 3, 3, 0, 1, 1, 3, 3, 3, 0, 1, 1, 3, 3, 3, 0, // 0x00B0
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, // 0x00C0
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, // 0x00D0
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, // 0x00E0
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 0x00F0
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, // 0x0100
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, // 0x0110
    0, 0, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // 0x0120
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, // 0x0130
};

inline bool canRead(uint16_t address) noexcept {
    return address < sizeof(ACCESS) && (ACCESS[address] & 1) != 0;
}

inline bool canWriteSingle(uint16_t address) noexcept {
    return address < sizeof(ACCESS) && (ACCESS[address] & 2) != 0;
}

} // namespace Detail
}} // namespace MotorControlRS::ESS_RS
