// Generated by scripts/generate_ess_registers.py; edit the JSON ledger.
#include "MotorControlRS/profiles/ess_rs/Registers.h"

namespace MotorControlRS { namespace ESS_RS {
namespace {
const RegisterDescriptor CATALOGUE[] = {
    // Function PDF pages 68.
    {0x0000, 1, RegisterAccess::READ_ONLY, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 68,
     "DRIVER_MODEL", "model code",
     "unspecified", "0x0305", "RO",
     "A table default/model code is not proof of the attached model."},
    // Function PDF pages 68.
    {0x0001, 1, RegisterAccess::READ_ONLY, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 68,
     "DRIVER_VERSION", "version code",
     "unspecified", "0x0100", "RO",
     "Source prints 0x010 0; no firmware compatibility inferred."},
    // Function PDF pages 68.
    {0x0002, 1, RegisterAccess::READ_ONLY, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 68,
     "ACTIVE_NODE", "slave address",
     "unspecified", "unspecified", "RO",
     "Current active communication node; distinct from custom/staged node."},
    // Function PDF pages 68, 18.
    {0x0003, 1, RegisterAccess::READ_ONLY, RegisterSignedness::BITFIELD,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000140u, 68,
     "DIP_STATUS", "bitfield",
     "unspecified", "unspecified", "RO",
     "Source describes SW1-SW7 in bits 0-6; ESS23 hardware has SW1-SW5. Hardware pp8,11 assign SW1 to termination and SW2-SW5 to address; the generic speed example p18 instead assigns address 1 using SW1. Preserve raw bits; mapping unqualified."},
    // Function PDF pages 68.
    {0x0006, 1, RegisterAccess::READ_ONLY, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000040u, 68,
     "ERROR_CODE", "alarm code",
     "0: normal; 1-5: error", "unspecified", "RO",
     "Hardware p12 labels only 1, 2, 3, 5; code 4 remains unnamed. Preserve unknown codes."},
    // Function PDF pages 68.
    {0x0007, 1, RegisterAccess::READ_ONLY, RegisterSignedness::BITFIELD,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 68,
     "MOTION_STATUS", "bitfield",
     "unspecified", "unspecified", "RO",
     "Bit 4 set means released, clear means enabled. Bits 7-15 undocumented; retain raw values."},
    // Function PDF pages 68, 69.
    {0x0008, 1, RegisterAccess::READ_ONLY, RegisterSignedness::BITFIELD,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 68,
     "INPUT_STATUS", "bitfield",
     "unspecified", "unspecified", "RO",
     "X0-X3 bits 0-3, bits 4-15 reserved; 0 invalid, 1 valid."},
    // Function PDF pages 69.
    {0x0009, 1, RegisterAccess::READ_ONLY, RegisterSignedness::BITFIELD,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 69,
     "OUTPUT_STATUS", "bitfield",
     "unspecified", "unspecified", "RO",
     "Y0-Y1 bits 0-1, bits 2-15 reserved; 0 invalid, 1 valid."},
    // Function PDF pages 69, 30.
    {0x000A, 2, RegisterAccess::READ_ONLY, RegisterSignedness::UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 69,
     "CURRENT_POSITION", "subdivision equivalent",
     "unspecified", "unspecified", "RO",
     "Open-loop commanded position; closed-loop encoder feedback in subdivision equivalents. Signedness is not specified here."},
    // Function PDF pages 69.
    {0x000C, 1, RegisterAccess::READ_ONLY, RegisterSignedness::UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000208u, 69,
     "CURRENT_SPEED", "unspecified",
     "unspecified", "unspecified", "RO",
     "Current running speed; this row supplies no unit, range or signed encoding."},
    // Function PDF pages 69.
    {0x0010, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 69,
     "DEFAULT_DIRECTION", "unspecified",
     "0-1", "0", "RW",
     ""},
    // Function PDF pages 69.
    {0x0011, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000004u, 69,
     "SUBDIVISION", "subdivision setting",
     "400-51200", "1000", "RW",
     "Source calls this Segment settings; mechanical/command/encoder relation needs resolution before engineering-unit conversion."},
    // Function PDF pages 69.
    {0x0013, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000040u, 69,
     "CUSTOM_NODE", "slave address",
     "0-255", "0", "RW",
     "Effective when address DIP switches are OFF. Hardware p11 identifies SW2-SW5 as address switches, requires custom addresses to be set and saved, and reserves all-ON for factory restore, not address 15. Activation timing of a saved custom node is unspecified. Library unicast policy 1-247 is separate from source range 0-255."},
    // Function PDF pages 69.
    {0x0014, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 69,
     "BAUD_RATE", "unspecified",
     "0-3", "0", "RW",
     "Requires power cycle after modification."},
    // Function PDF pages 69.
    {0x0015, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 69,
     "SERIAL_FORMAT", "unspecified",
     "0-3", "0", "RW",
     "Requires power cycle after modification."},
    // Function PDF pages 70.
    {0x0017, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000400u, 70,
     "OVER_LIMIT_STOP", "unspecified",
     "0-1", "0", "RW",
     "Value 0 described only as free parking; do not assume controlled deceleration or release."},
    // Function PDF pages 70, 28, 29.
    {0x0018, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000100u, 70,
     "SOFT_LIMIT_ENABLE", "unspecified",
     "0-1", "0", "RW",
     "Enabled limits take effect only after homing. Prose p28 says 0x0019; table p29 and appendix say 0x0018."},
    // Function PDF pages 70, 30.
    {0x0019, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 70,
     "WORD_ORDER", "unspecified",
     "0-1", "0", "RW",
     "Order of paired 16-bit words, not byte order within a Modbus register."},
    // Function PDF pages 70, 17, 18, 19.
    {0x001D, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000010Fu, 70,
     "JOG_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "120 (5 r/min)", "RW",
     "Serial speed mode uses this signed speed. External JOG+/JOG- force direction independently of sign. The p18 example writes positive 0x003C for 60 r/min although its introduction says reverse and 500 r/min; it is not evidence for negative encoding. No refresh watchdog specified."},
    // Function PDF pages 70, 17.
    {0x001E, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 70,
     "JOG_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "50 (100 ms)", "RW",
     "Conflicting default annotation retained; no factor-of-two scaling inferred."},
    // Function PDF pages 70, 17, 25.
    {0x001F, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 70,
     "JOG_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "50 (100 ms)", "RW",
     "Conflicting default annotation retained; no factor-of-two scaling inferred. Normal stop uses the deceleration time configured before motion starts; changing it during motion does not change that stop ramp (p25)."},
    // Function PDF pages 70, 16.
    {0x0020, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 70,
     "POSITION_START_SPEED", "r/min (documented)",
     "0-3000 r/min", "30 (60 r/min)", "RW",
     "The p16 motion example mentions initial speed 10 r/min but starts its parameter write at 0x0021, leaving this register unchanged. Do not treat that example as a complete start-speed configuration."},
    // Function PDF pages 70, 15.
    {0x0021, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 70,
     "POSITION_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "50 (100 ms)", "RW",
     "Conflicting default annotation retained; no factor-of-two scaling inferred."},
    // Function PDF pages 70, 15, 25.
    {0x0022, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 70,
     "POSITION_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "50 (100 ms)", "RW",
     "Conflicting default annotation retained; no factor-of-two scaling inferred. Normal stop uses the deceleration time configured before motion starts; changing it during motion does not change that stop ramp (p25)."},
    // Function PDF pages 70, 15.
    {0x0023, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 70,
     "POSITION_SPEED", "r/min (documented)",
     "0-3000 r/min", "60 (60 r/min)", "RW",
     ""},
    // Function PDF pages 70, 14, 16, 30.
    {0x0024, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Eu, 70,
     "POSITION_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFFF (as printed)", "5000 (combined pair)", "RW",
     "Positive/negative direction documented; two-register width documented; full signed range/negative encoding unresolved."},
    // Function PDF pages 70, 71, 13, 14, 16, 18, 19, 25.
    {0x0027, 1, RegisterAccess::WRITE_ONLY, RegisterSignedness::BITFIELD,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000500u, 70,
     "MOTION_COMMAND", "bitfield",
     "0-65535", "-", "WO",
     "Only named bits are catalogued, no arbitrary combinations validated. Bit 3 interrupt applies only positioning per p16. p25 stop table text contradicts labels/examples; stop examples confirm bits 8/9. Normal stop decelerates using the pre-motion ramp; emergency stop is described as direct stop without deceleration, not motor release. No command queue depth, watchdog deadline or stop-completion latency is specified."},
    // Function PDF pages 71, 26.
    {0x002D, 1, RegisterAccess::WRITE_ONLY, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 71,
     "AUXILIARY_COMMAND", "opcode",
     "0-65535", "-", "WO",
     "Save/factory restore ignored unless stopped. Clear-alarm only applies resettable alarms. No generic reboot opcode."},
    // Function PDF pages 72.
    {0x0030, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 72,
     "HOMING_AUXILIARY", "unspecified",
     "0-11", "0", "RW",
     ""},
    // Function PDF pages 72, 19.
    {0x0031, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000108u, 72,
     "HOMING_METHOD", "unspecified",
     "0-65535; listed choices: -1 through -4, 1-14, 17-30, 33-35", "24 (printed twenty four)", "RW",
     "Negative collision modes appear only in ESS appendix, absent from positive-method diagrams/prose. Negative wire encoding is unresolved."},
    // Function PDF pages 72, 19, 20.
    {0x0032, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 72,
     "HOMING_SPEED", "r/min (documented)",
     "5-3000 r/min", "120 (60 r/min)", "RW",
     ""},
    // Function PDF pages 73, 19, 20.
    {0x0033, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 73,
     "HOMING_QUERY_SPEED", "r/min (documented)",
     "5-300 r/min", "60 (60 r/min)", "RW",
     ""},
    // Function PDF pages 73, 19, 20.
    {0x0034, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 73,
     "HOMING_RAMP_TIME", "ms (documented)",
     "30-2000 ms", "50 (100 ms)", "RW",
     ""},
    // Function PDF pages 73, 19, 30.
    {0x0035, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::UNRESOLVED, 0x0000008Cu, 73,
     "HOMING_OFFSET", "native position; scale unresolved",
     "-0xFFFFFFF to 0xFFFFFFF", "0 (combined pair)", "RW",
     "High/low pair documented; omitted from p30 list of configurable-order pairs. Do not silently assume applies."},
    // Function PDF pages 73, 29, 30.
    {0x0037, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 73,
     "POSITIVE_SOFT_LIMIT", "native position; scale unresolved",
     "-0xFFFFFFF to 0xFFFFFFF", "0 (combined pair)", "RW",
     "Limit applies only after homing completes."},
    // Function PDF pages 73, 29, 30.
    {0x0039, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 73,
     "NEGATIVE_SOFT_LIMIT", "native position; scale unresolved",
     "-0xFFFFFFF to 0xFFFFFFF", "0 (combined pair)", "RW",
     "Limit applies only after homing completes."},
    // Function PDF pages 73.
    {0x003B, 1, RegisterAccess::UNSPECIFIED, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000230u, 73,
     "COLLISION_THRESHOLD_003B", "position error; unit unspecified",
     "50-4000", "200", "UNSPECIFIED",
     "Applies collision modes -1 through -4. Separate 0x0122 row has different lower bound; aliasing/model applicability unresolved."},
    // Function PDF pages 73.
    {0x003C, 1, RegisterAccess::UNSPECIFIED, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000030u, 73,
     "COLLISION_CURRENT_003C", "percent",
     "20-100", "50", "UNSPECIFIED",
     "Applies collision modes -1 through -4. Separate 0x0123 row; aliasing/model applicability unresolved."},
    // Function PDF pages 73.
    {0x0040, 1, RegisterAccess::READ_WRITE, RegisterSignedness::BITFIELD,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 73,
     "INPUT_POLARITY", "bitfield",
     "0-65535", "0", "RW",
     "Bits 0-3 default 0 / inverted 1; bits 4-15 reserved."},
    // Function PDF pages 73, 74, 14, 27.
    {0x0041, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 73,
     "INPUT_X0_FUNCTION", "unspecified",
     "0-17", "1", "RW",
     "Only X0-X3 in ESS appendix; generic prose 0x0041-0x0047 is not additional ESS pins."},
    // Function PDF pages 73, 74, 14, 27.
    {0x0042, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 73,
     "INPUT_X1_FUNCTION", "unspecified",
     "0-17", "2", "RW",
     "Only X0-X3 in ESS appendix; generic prose 0x0041-0x0047 is not additional ESS pins."},
    // Function PDF pages 73, 74, 14, 27.
    {0x0043, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 73,
     "INPUT_X2_FUNCTION", "unspecified",
     "0-17", "3", "RW",
     "Only X0-X3 in ESS appendix; generic prose 0x0041-0x0047 is not additional ESS pins."},
    // Function PDF pages 73, 74, 14, 27.
    {0x0044, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 73,
     "INPUT_X3_FUNCTION", "unspecified",
     "0-17", "0", "RW",
     "Only X0-X3 in ESS appendix; generic prose 0x0041-0x0047 is not additional ESS pins."},
    // Function PDF pages 74.
    {0x004B, 1, RegisterAccess::READ_WRITE, RegisterSignedness::BITFIELD,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 74,
     "OUTPUT_POLARITY", "bitfield",
     "0-65535", "0", "RW",
     "Bits 0-1 default 0 / inverted 1; bits 2-15 reserved."},
    // Function PDF pages 74, 28.
    {0x004C, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000400u, 74,
     "OUTPUT_Y0_FUNCTION", "unspecified",
     "0-11; values6, 7, 8 not described", "0", "RW",
     "Custom value 11 is listed despite only two ESS outputs; exact custom-selector mapping unresolved. Generic 0x004E is not an ESS output register."},
    // Function PDF pages 74, 28.
    {0x004D, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000400u, 74,
     "OUTPUT_Y1_FUNCTION", "unspecified",
     "0-11; values6, 7, 8 not described", "0", "RW",
     "Custom value 11 is listed despite only two ESS outputs; exact custom-selector mapping unresolved. Generic 0x004E is not an ESS output register."},
    // Function PDF pages 74, 28.
    {0x004F, 1, RegisterAccess::READ_WRITE, RegisterSignedness::BITFIELD,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 74,
     "CUSTOM_OUTPUT", "bitfield",
     "0-65535", "0", "RW",
     "Y0/Y1 bits 0/1; bits 2-15 reserved; applicable to outputs configured custom."},
    // Function PDF pages 75, 23.
    {0x0050, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 75,
     "EXTERNAL_POSITION_MODE", "unspecified",
     "0-1", "0", "RW",
     "Only external-input position/multisegment operation; serial position selects bit 2 in 0x0027."},
    // Function PDF pages 75, 29.
    {0x0051, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 75,
     "PV_TRIGGER_MODE", "unspecified",
     "0-1", "0", "RW",
     "Value 1 required to mix multivelocity and multiposition fixed-length interruption."},
    // Function PDF pages 75, 22, 23, 76.
    {0x0060, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 75,
     "POSITION_SEGMENT_01_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 75, 22, 23, 76.
    {0x0062, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_01_SPEED", "r/min (documented)",
     "0-3000 r/min", "120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0063, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_01_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0064, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_01_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0065, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 75,
     "POSITION_SEGMENT_01_RESERVED", "reserved",
     "0", "0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 75, 22, 23, 76.
    {0x0066, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 75,
     "POSITION_SEGMENT_02_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 75, 22, 23, 76.
    {0x0068, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_02_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0069, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_02_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x006A, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_02_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x006B, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 75,
     "POSITION_SEGMENT_02_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 75, 22, 23, 76.
    {0x006C, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 75,
     "POSITION_SEGMENT_03_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 75, 22, 23, 76.
    {0x006E, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_03_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x006F, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_03_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0070, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_03_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0071, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 75,
     "POSITION_SEGMENT_03_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 75, 22, 23, 76.
    {0x0072, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 75,
     "POSITION_SEGMENT_04_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 75, 22, 23, 76.
    {0x0074, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_04_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0075, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_04_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0076, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_04_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0077, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 75,
     "POSITION_SEGMENT_04_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 75, 22, 23, 76.
    {0x0078, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 75,
     "POSITION_SEGMENT_05_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 75, 22, 23, 76.
    {0x007A, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_05_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x007B, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_05_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x007C, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_05_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x007D, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 75,
     "POSITION_SEGMENT_05_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 75, 22, 23, 76.
    {0x007E, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 75,
     "POSITION_SEGMENT_06_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 75, 22, 23, 76.
    {0x0080, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_06_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0081, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_06_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0082, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_06_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0083, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 75,
     "POSITION_SEGMENT_06_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 75, 22, 23, 76.
    {0x0084, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 75,
     "POSITION_SEGMENT_07_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 75, 22, 23, 76.
    {0x0086, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_07_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0087, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_07_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0088, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_07_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x0089, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 75,
     "POSITION_SEGMENT_07_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 75, 22, 23, 76.
    {0x008A, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 75,
     "POSITION_SEGMENT_08_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 75, 22, 23, 76.
    {0x008C, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_08_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x008D, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_08_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x008E, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 75,
     "POSITION_SEGMENT_08_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 75, 22, 23, 76.
    {0x008F, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 75,
     "POSITION_SEGMENT_08_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 76, 22, 23, 75.
    {0x0090, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 76,
     "POSITION_SEGMENT_09_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 76, 22, 23, 75.
    {0x0092, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_09_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x0093, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_09_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x0094, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_09_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x0095, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 76,
     "POSITION_SEGMENT_09_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 76, 22, 23, 75.
    {0x0096, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 76,
     "POSITION_SEGMENT_10_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 76, 22, 23, 75.
    {0x0098, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_10_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x0099, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_10_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x009A, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_10_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x009B, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 76,
     "POSITION_SEGMENT_10_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 76, 22, 23, 75.
    {0x009C, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 76,
     "POSITION_SEGMENT_11_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 76, 22, 23, 75.
    {0x009E, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_11_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x009F, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_11_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00A0, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_11_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00A1, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 76,
     "POSITION_SEGMENT_11_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 76, 22, 23, 75.
    {0x00A2, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 76,
     "POSITION_SEGMENT_12_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 76, 22, 23, 75.
    {0x00A4, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_12_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00A5, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_12_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00A6, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_12_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00A7, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 76,
     "POSITION_SEGMENT_12_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 76, 22, 23, 75.
    {0x00A8, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 76,
     "POSITION_SEGMENT_13_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 76, 22, 23, 75.
    {0x00AA, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_13_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00AB, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_13_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00AC, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_13_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00AD, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 76,
     "POSITION_SEGMENT_13_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 76, 22, 23, 75.
    {0x00AE, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 76,
     "POSITION_SEGMENT_14_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 76, 22, 23, 75.
    {0x00B0, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_14_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00B1, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_14_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00B2, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_14_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00B3, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 76,
     "POSITION_SEGMENT_14_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 76, 22, 23, 75.
    {0x00B4, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 76,
     "POSITION_SEGMENT_15_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 76, 22, 23, 75.
    {0x00B6, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_15_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00B7, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_15_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00B8, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_15_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00B9, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 76,
     "POSITION_SEGMENT_15_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 76, 22, 23, 75.
    {0x00BA, 2, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::CONFIGURABLE, 0x0000000Cu, 76,
     "POSITION_SEGMENT_16_PULSES", "pulse",
     "-0xFFFFFFF to 0xFFFFFFF", "not separately stated; first-segment template: high 0; low 5000", "RW",
     "Defaults explicitly listed for first segment only; later instance defaults not independently stated."},
    // Function PDF pages 76, 22, 23, 75.
    {0x00BC, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_16_SPEED", "r/min (documented)",
     "0-3000 r/min", "not separately stated; first-segment template: 120 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00BD, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_16_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00BE, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "POSITION_SEGMENT_16_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 22, 23, 75.
    {0x00BF, 1, RegisterAccess::RESERVED, RegisterSignedness::RESERVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 76,
     "POSITION_SEGMENT_16_RESERVED", "reserved",
     "0", "not separately stated; first-segment template: 0", "RW/S",
     "Explicit reserve row; metadata access is RESERVED despite printedRW/S; no writes offered."},
    // Function PDF pages 76, 23, 24, 77.
    {0x00C0, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 76,
     "SPEED_SEGMENT_01_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00C1, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_01_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00C2, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_01_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00C3, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 76,
     "SPEED_SEGMENT_02_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00C4, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_02_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00C5, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_02_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00C6, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 76,
     "SPEED_SEGMENT_03_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00C7, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_03_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00C8, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_03_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00C9, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 76,
     "SPEED_SEGMENT_04_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00CA, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_04_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00CB, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_04_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00CC, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 76,
     "SPEED_SEGMENT_05_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00CD, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_05_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00CE, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_05_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00CF, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 76,
     "SPEED_SEGMENT_06_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00D0, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_06_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00D1, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_06_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00D2, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 76,
     "SPEED_SEGMENT_07_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00D3, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_07_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00D4, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_07_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00D5, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 76,
     "SPEED_SEGMENT_08_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00D6, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_08_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 76, 23, 24, 77.
    {0x00D7, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 76,
     "SPEED_SEGMENT_08_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00D8, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 77,
     "SPEED_SEGMENT_09_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00D9, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_09_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00DA, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_09_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00DB, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 77,
     "SPEED_SEGMENT_10_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00DC, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_10_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00DD, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_10_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00DE, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 77,
     "SPEED_SEGMENT_11_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00DF, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_11_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00E0, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_11_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00E1, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 77,
     "SPEED_SEGMENT_12_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00E2, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_12_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00E3, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_12_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00E4, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 77,
     "SPEED_SEGMENT_13_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00E5, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_13_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00E6, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_13_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00E7, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 77,
     "SPEED_SEGMENT_14_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00E8, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_14_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00E9, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_14_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00EA, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 77,
     "SPEED_SEGMENT_15_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00EB, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_15_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00EC, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_15_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00ED, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x0000000Fu, 77,
     "SPEED_SEGMENT_16_SPEED", "r/min (documented)",
     "-3000 -3000 r/min (as printed)", "not separately stated; first-segment template: 100 (0/min)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00EE, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_16_ACCELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77, 23, 24, 76.
    {0x00EF, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000005u, 77,
     "SPEED_SEGMENT_16_DECELERATION_TIME", "ms (documented)",
     "0-2000 ms", "not separately stated; first-segment template: 50 (0 ms)", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x0100, 1, RegisterAccess::READ_WRITE, RegisterSignedness::ENUMERATED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 77,
     "CONTROL_ALGORITHM", "unspecified",
     "1-2", "2", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x0101, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 77,
     "ENCODER_RESOLUTION", "counts (four times encoder line count)",
     "0-65535", "4000", "RW/S",
     "The source explicitly defines counts as four times the encoder line count; its default of 4000 corresponds to 1000 lines. This documented scale does not establish the active device value or the separate command-subdivision configuration."},
    // Function PDF pages 77.
    {0x0102, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000041u, 77,
     "MAXIMUM_CURRENT", "mA",
     "0-5600", "5600/2200", "RW/S",
     "Default column gives two values without model mapping; do not select one."},
    // Function PDF pages 77.
    {0x0103, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000100u, 77,
     "CLOSED_LOOP_CURRENT_PERCENT", "percent",
     "0-150", "100", "RW/S",
     "Prose references 0x2042 current register outside ESS map; do not create a 0x2042 alias or assume 0x0102 automatically."},
    // Function PDF pages 78.
    {0x0104, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000100u, 78,
     "BASE_CURRENT_PERCENT", "percent",
     "0-75", "40", "RW/S",
     "Prose references 0x2042 current register outside ESS map; do not create a 0x2042 alias or assume 0x0102 automatically."},
    // Function PDF pages 78.
    {0x0105, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000100u, 78,
     "OPEN_LOOP_CURRENT_PERCENT", "percent",
     "0-100", "100", "RW/S",
     "Prose references 0x2042 current register outside ESS map; do not create a 0x2042 alias or assume 0x0102 automatically."},
    // Function PDF pages 78.
    {0x0106, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000100u, 78,
     "LOCK_CURRENT_PERCENT", "percent",
     "0-100", "100", "RW/S",
     "Prose references 0x2042 current register outside ESS map; do not create a 0x2042 alias or assume 0x0102 automatically."},
    // Function PDF pages 78.
    {0x0107, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 78,
     "LOCK_TIME", "ms",
     "0-20000", "4000", "RW/S",
     "Delay after movement stops before the motor enters the lock state, in ms. It is not a communication timeout or a guaranteed motion-completion delay."},
    // Function PDF pages 78.
    {0x0108, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 78,
     "INPUT_FILTER", "coefficient",
     "0-65535", "2", "RW/S",
     "Terminal filter coefficient only; the source supplies no time unit or coefficient-to-delay formula."},
    // Function PDF pages 78.
    {0x0109, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 78,
     "PULSE_LOW_PASS_FILTER", "coefficient",
     "0-1024", "5", "RW/S",
     "Pulse-command low-pass filter coefficient; a smaller value gives a stronger filtering effect. No coefficient-to-time formula is stated."},
    // Function PDF pages 78.
    {0x010A, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 78,
     "POSITION_ERROR_ALARM_THRESHOLD", "unspecified",
     "1-65535", "4000", "RW/S",
     "The source names a position-deviation threshold but supplies no count basis. Do not assume raw encoder counts or command subdivisions."},
    // Function PDF pages 78.
    {0x010B, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 78,
     "POSITION_ARRIVAL_WINDOW", "unspecified",
     "1-256", "5", "RW/S",
     "The source names a positioning-error range but supplies no count basis. It is not sufficient by itself to establish motion completion."},
    // Function PDF pages 78.
    {0x010C, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 78,
     "ARRIVAL_TIME", "unspecified",
     "0-200", "10", "RW/S",
     "The source names an arrival/end time but supplies no unit or timing rule. Do not infer milliseconds from neighboring registers."},
    // Function PDF pages 78.
    {0x010D, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 78,
     "PULSE_MEAN_FILTER", "coefficient",
     "0-512", "512", "RW/S",
     "Mean filter coefficient; a larger value gives a stronger filtering effect. No coefficient-to-time formula is stated."},
    // Function PDF pages 78.
    {0x010E, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000000u, 78,
     "CURRENT_LOOP_KP_MULTIPLIER", "gain",
     "0-65535", "4096", "RW/S",
     ""},
    // Function PDF pages 79.
    {0x010F, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 79,
     "CURRENT_LOOP_KP", "unspecified",
     "0-65535", "1024", "RW/S",
     ""},
    // Function PDF pages 79.
    {0x0110, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 79,
     "CURRENT_LOOP_KI", "unspecified",
     "0-65535", "28", "RW/S",
     ""},
    // Function PDF pages 79.
    {0x0111, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 79,
     "CURRENT_LOOP_KC", "unspecified",
     "0-65535", "1228", "RW/S",
     ""},
    // Function PDF pages 79.
    {0x0112, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 79,
     "LA_SPEED_KP1", "unspecified",
     "0-65535", "10", "RW/S",
     ""},
    // Function PDF pages 79.
    {0x0113, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 79,
     "LA_SPEED_KV1", "unspecified",
     "0-65535", "32", "RW/S",
     ""},
    // Function PDF pages 79.
    {0x0114, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 79,
     "LA_SPEED_NODE1", "unspecified",
     "0-65535", "320", "RW/S",
     ""},
    // Function PDF pages 79.
    {0x0115, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 79,
     "LA_SPEED_KP2", "unspecified",
     "0-65535", "15", "RW/S",
     ""},
    // Function PDF pages 79.
    {0x0116, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 79,
     "LA_SPEED_KV2", "unspecified",
     "0-65535", "33", "RW/S",
     ""},
    // Function PDF pages 79.
    {0x0117, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 79,
     "LA_SPEED_NODE2", "unspecified",
     "0-65535", "320", "RW/S",
     ""},
    // Function PDF pages 79.
    {0x0118, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 79,
     "LA_SPEED_FEEDFORWARD_KVF", "unspecified",
     "0-65535", "20", "RW/S",
     ""},
    // Function PDF pages 79.
    {0x0119, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000200u, 79,
     "LA_POSITION_KI", "unspecified",
     "0-65535", "35", "RW/S",
     ""},
    // Function PDF pages 79.
    {0x0122, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000220u, 79,
     "COLLISION_THRESHOLD_0122", "position error; unit unspecified",
     "200-4000", "200", "RW/S",
     "Compare 0x003B lower bound 50 and absent access marker; retain separate entries."},
    // Function PDF pages 79.
    {0x0123, 1, RegisterAccess::READ_WRITE, RegisterSignedness::UNSIGNED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000020u, 79,
     "COLLISION_CURRENT_0123", "percent",
     "20-100", "50", "RW/S",
     "Compare 0x003C; relationship unestablished."},
    // Function PDF pages 77.
    {0x0130, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_01_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x0131, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_02_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x0132, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_03_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x0133, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_04_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x0134, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_05_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x0135, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_06_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x0136, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_07_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x0137, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_08_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x0138, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_09_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x0139, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_10_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x013A, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_11_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x013B, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_12_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x013C, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_13_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x013D, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_14_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x013E, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_15_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
    // Function PDF pages 77.
    {0x013F, 1, RegisterAccess::READ_WRITE, RegisterSignedness::SIGNED_ENCODING_UNRESOLVED,
     RegisterWordOrder::SINGLE_REGISTER, 0x00000008u, 77,
     "SEGMENT_START_SPEED_16_VALUE", "rpm (documented)",
     "-180 to180 rpm", "0 rpm", "RW/S",
     ""},
};

const HomingMethodDescriptor HOMING_METHODS[] = {
    {-4, 72, false, true, "Collision mode listed in ESS table; trajectory and negative wire encoding unresolved."},
    {-3, 72, false, true, "Collision mode listed in ESS table; trajectory and negative wire encoding unresolved."},
    {-2, 72, false, true, "Collision mode listed in ESS table; trajectory and negative wire encoding unresolved."},
    {-1, 72, false, true, "Collision mode listed in ESS table; trajectory and negative wire encoding unresolved."},
    {1, 32, true, false, "Method 1: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {2, 33, true, false, "Method 2: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {3, 34, true, false, "Method 3: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {4, 34, true, false, "Method 4: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {5, 35, true, false, "Method 5: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {6, 36, true, false, "Method 6: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {7, 37, true, false, "Method 7: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {8, 39, true, false, "Method 8: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {9, 40, true, false, "Method 9: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {10, 42, true, false, "Method 10: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {11, 44, true, false, "Method 11: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {12, 45, true, false, "Method 12: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {13, 47, true, false, "Method 13: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {14, 49, true, false, "Method 14: reference motor Z index; use cited diagrams for starting-state-dependent paths."},
    {17, 50, false, false, "Method 17: reference negative limit; use cited diagrams for starting-state-dependent paths."},
    {18, 51, false, true, "Method 18: reference positive limit; use cited diagrams for starting-state-dependent paths. Figure labels negative limit conflict with positive-limit prose; retain discrepancy."},
    {19, 52, false, false, "Method 19: reference origin input; use cited diagrams for starting-state-dependent paths."},
    {20, 52, false, false, "Method 20: reference origin input; use cited diagrams for starting-state-dependent paths."},
    {21, 53, false, false, "Method 21: reference origin input; use cited diagrams for starting-state-dependent paths."},
    {22, 54, false, false, "Method 22: reference origin input; use cited diagrams for starting-state-dependent paths."},
    {23, 55, false, false, "Method 23: reference origin input; use cited diagrams for starting-state-dependent paths."},
    {24, 57, false, false, "Method 24: reference origin input; use cited diagrams for starting-state-dependent paths."},
    {25, 58, false, false, "Method 25: reference origin input; use cited diagrams for starting-state-dependent paths."},
    {26, 60, false, false, "Method 26: reference origin input; use cited diagrams for starting-state-dependent paths."},
    {27, 61, false, false, "Method 27: reference origin input; use cited diagrams for starting-state-dependent paths."},
    {28, 63, false, false, "Method 28: reference origin input; use cited diagrams for starting-state-dependent paths."},
    {29, 64, false, false, "Method 29: reference origin input; use cited diagrams for starting-state-dependent paths."},
    {30, 66, false, false, "Method 30: reference origin input; use cited diagrams for starting-state-dependent paths."},
    {33, 67, true, false, "Method 33: negative low-speed search for motor Z index; no slowdown input."},
    {34, 67, true, false, "Method 34: positive low-speed search for motor Z index; no slowdown input."},
    {35, 67, false, false, "Method 35: source says set current position as origin; not a sensor-search motion."},
};
} // namespace

std::size_t registerCount() noexcept {
    return sizeof(CATALOGUE) / sizeof(CATALOGUE[0]);
}

const RegisterDescriptor* registerAt(std::size_t index) noexcept {
    return index < registerCount() ? &CATALOGUE[index] : nullptr;
}

const RegisterDescriptor* findRegister(uint16_t address) noexcept {
    std::size_t first = 0;
    std::size_t last = registerCount();
    while (first < last) {
        const std::size_t middle = first + (last - first) / 2;
        const RegisterDescriptor& entry = CATALOGUE[middle];
        if (address < entry.address) {
            last = middle;
        } else if (static_cast<uint32_t>(address) >= static_cast<uint32_t>(entry.address) + entry.wordCount) {
            first = middle + 1;
        } else {
            return &entry;
        }
    }
    return nullptr;
}

bool hasRegisterIssue(const RegisterDescriptor& entry, RegisterIssue issue) noexcept {
    const uint32_t mask = static_cast<uint32_t>(issue);
    return mask != 0 && (entry.issues & mask) == mask;
}

const RegisterDescriptor* positionSegmentRegister(uint8_t segment, PositionSegmentField field) noexcept {
    if (segment < 1 || segment > 16) return nullptr;
    const uint8_t offset = static_cast<uint8_t>(field);
    if (offset != 0 && offset != 2 && offset != 3 && offset != 4 && offset != 5) return nullptr;
    return findRegister(static_cast<uint16_t>(Registers::POSITION_SEGMENT_01_PULSES + (segment - 1) * 6 + offset));
}

const RegisterDescriptor* speedSegmentRegister(uint8_t segment, SpeedSegmentField field) noexcept {
    if (segment < 1 || segment > 16) return nullptr;
    const uint8_t offset = static_cast<uint8_t>(field);
    if (offset > 2) return nullptr;
    return findRegister(static_cast<uint16_t>(Registers::SPEED_SEGMENT_01_SPEED + (segment - 1) * 3 + offset));
}

const RegisterDescriptor* segmentStartSpeedRegister(uint8_t segment) noexcept {
    if (segment < 1 || segment > 16) return nullptr;
    return findRegister(static_cast<uint16_t>(Registers::SEGMENT_START_SPEED_01_VALUE + segment - 1));
}

const RegisterDescriptor* inputFunctionRegister(uint8_t terminal) noexcept {
    return terminal < 4 ? findRegister(static_cast<uint16_t>(Registers::INPUT_X0_FUNCTION + terminal)) : nullptr;
}

const RegisterDescriptor* outputFunctionRegister(uint8_t terminal) noexcept {
    return terminal < 2 ? findRegister(static_cast<uint16_t>(Registers::OUTPUT_Y0_FUNCTION + terminal)) : nullptr;
}

std::size_t homingMethodCount() noexcept {
    return sizeof(HOMING_METHODS) / sizeof(HOMING_METHODS[0]);
}

const HomingMethodDescriptor* findHomingMethod(int16_t method) noexcept {
    for (std::size_t i = 0; i < homingMethodCount(); ++i) {
        if (HOMING_METHODS[i].method == method) return &HOMING_METHODS[i];
    }
    return nullptr;
}

}} // namespace MotorControlRS::ESS_RS
