#!/usr/bin/env python3
"""Generate the ESS source catalogue; --check reports stale generated files.

The JSON ledger is the only editable register/choice table. This generator
does not infer ranges, persistence, signed encodings, or device support.
"""

import argparse
import copy
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "docs/reference/ess_rs_registers.json"
PUBLIC = ROOT / "include/MotorControlRS/profiles/ess_rs"
NOTICE = "// Generated by scripts/generate_ess_registers.py; edit the JSON ledger.\n"
OPEN_NS = "namespace MotorControlRS { namespace ESS_RS {\n"
CLOSE_NS = "}} // namespace MotorControlRS::ESS_RS\n"


def quoted(value):
    return json.dumps(value, ensure_ascii=True)


def expand(data):
    rows = copy.deepcopy(data["registers"])
    for group in data["indexed_groups"]:
        for instance in group["instances"]:
            for template in group["templates"]:
                row = copy.deepcopy(template)
                row["address"] = "0x%04X" % (int(instance["base"], 16) + row.pop("offset"))
                row["name"] = "%s_%02d_%s" % (group["name"], instance["index"], row["name"])
                row["pages"] = list(dict.fromkeys([instance["page"]] + group["pages"]))
                if instance["index"] != 1 and group["name"] != "SEGMENT_START_SPEED":
                    row["source_default"] = "not separately stated; first-segment template: " + row["source_default"]
                rows.append(row)
    return sorted(rows, key=lambda row: int(row["address"], 16))


def validate(data, rows):
    occupied = set()
    names = set()
    for row in rows:
        address = int(row["address"], 16)
        if row["name"] in names or row["words"] not in (1, 2):
            raise ValueError("duplicate name or invalid width: " + row["name"])
        names.add(row["name"])
        for word in range(address, address + row["words"]):
            if word in occupied or not 0 <= word <= 0x13F:
                raise ValueError("overlap or outside ESS catalogue: " + row["name"])
            occupied.add(word)
        if not row["pages"] or any(p < 13 or p > 79 for p in row["pages"]):
            raise ValueError("invalid source page: " + row["name"])
        for issue in row["issues"]:
            if issue not in data["issues"]:
                raise ValueError("unknown issue: " + issue)
    counts = data["complete_source_catalogue"]
    actual = (len(rows), len(occupied), sum(r["words"] == 2 for r in rows),
              sum(r["signedness"] == "RESERVED" for r in rows))
    expected = tuple(counts[k] for k in ("logical_descriptors", "register_words", "paired_records", "explicit_reserved_words"))
    if actual != expected:
        raise ValueError("catalogue count mismatch: %r != %r" % (actual, expected))
    coverage = data["address_coverage"]
    first, last = int(coverage["first"], 16), int(coverage["last"], 16)
    if (first, last) != (0, 0x13F):
        raise ValueError("unexpected audited ESS address span")
    gaps = set()
    for gap in coverage["gaps"]:
        begin, end = int(gap["first"], 16), int(gap["last"], 16)
        words = set(range(begin, end + 1))
        if begin > end or begin < first or end > last or words & (occupied | gaps):
            raise ValueError("overlapping or invalid gap: " + gap["first"])
        if not gap["pages"] or any(page < 68 or page > 79 for page in gap["pages"]):
            raise ValueError("gap needs ESS appendix evidence")
        gaps.update(words)
    if occupied | gaps != set(range(first, last + 1)):
        raise ValueError("registers and audited gaps must cover the entire ESS span")
    if (len(occupied), len(gaps)) != (coverage["documented_words"], coverage["gap_words"]):
        raise ValueError("address coverage count mismatch")
    if (len(gaps), len(coverage["gaps"])) != (counts["undocumented_words_in_span"],
                                               counts["undocumented_intervals_in_span"]):
        raise ValueError("catalogue gap summary mismatch")
    for key, predicate in (
        ("explicit_reserved", lambda row: row["signedness"] == "RESERVED"),
        ("access_unspecified", lambda row: row["source_access"] == "UNSPECIFIED"),
    ):
        actual_words = {word for row in rows if predicate(row)
                        for word in range(int(row["address"], 16), int(row["address"], 16) + row["words"])}
        listed_words = [int(word, 16) for word in coverage[key]]
        if set(listed_words) != actual_words or len(listed_words) != len(actual_words):
            raise ValueError("coverage category mismatch: " + key)
    for enum in data["enums"]:
        values = [v["value"] for v in enum["values"]]
        if len(values) != len(set(values)):
            raise ValueError("duplicate enum value: " + enum["name"])
    for group in data["indexed_groups"]:
        if [i["index"] for i in group["instances"]] != list(range(1, group["count"] + 1)):
            raise ValueError("missing indexed instance: " + group["name"])
        start = int(group["instances"][0]["base"], 16)
        for i in group["instances"]:
            expected_base = start + (i["index"] - 1) * group["stride"]
            if int(i["base"], 16) != expected_base or int(i["last"], 16) != expected_base + group["stride"] - 1:
                raise ValueError("invalid indexed range: " + group["name"])
    validate_write_windows(data, rows)
    return occupied


def validate_write_windows(data, rows):
    """Validate explicit source windows; writable adjacency never grants FC10."""
    by_word = {word: row for row in rows for word in
               range(int(row["address"], 16), int(row["address"], 16) + row["words"])}
    seen = set()
    windows = data["write_multiple_windows"]
    if not windows:
        raise ValueError("missing reviewed FC10 windows")
    for window in windows:
        start, count = int(window["start"], 16), window["count"]
        # Structural frame-buffer bound only, never an inferred device maximum.
        if (type(count) is not int or count < 1 or 9 + 2 * count > 256 or start < 0 or
                start + count > 0x140 or (start, count) in seen):
            raise ValueError("invalid or duplicate FC10 window")
        seen.add((start, count))
        if (not window["pages"] or any(type(page) is not int or not 1 <= page <= 79
                                       for page in window["pages"]) or
                not isinstance(window["evidence"], str) or not window["evidence"].strip()):
            raise ValueError("FC10 window requires ESS source evidence")
        if window["partial_application"] != "UNSPECIFIED":
            raise ValueError("no ESS atomic-write guarantee has been established")
        for word in range(start, start + count):
            row = by_word.get(word)
            if (row is None or row["source_access"] not in ("WO", "RW", "RW/S") or
                    row["signedness"] == "RESERVED"):
                raise ValueError("FC10 window contains a gap or nonwritable word")
            first = int(row["address"], 16)
            if first < start or first + row["words"] > start + count:
                raise ValueError("FC10 window splits a paired field")
    for row in rows:
        if row["words"] == 2 and row["source_access"] in ("WO", "RW", "RW/S"):
            if not isinstance(row.get("write_constraint"), str) or not row["write_constraint"].strip():
                raise ValueError("writable pair requires an explicit disposition: " + row["name"])


def types_header(data):
    lines = [NOTICE, "#pragma once\n\n#include <stdint.h>\n\n", OPEN_NS]
    lines += ["\n/** Source access only; it is not authorization to perform a transaction. */\n",
              "enum class RegisterAccess : uint8_t { READ_ONLY, WRITE_ONLY, READ_WRITE, UNSPECIFIED, RESERVED };\n",
              "/** Signed semantic values are distinguished from an established wire encoding. */\n",
              "enum class RegisterSignedness : uint8_t { UNSIGNED, SIGNED_ENCODING_UNRESOLVED, BITFIELD, ENUMERATED, UNRESOLVED, RESERVED };\n",
              "/** CONFIGURABLE requires an explicit active WordOrder; it never supplies a default. */\n",
              "enum class RegisterWordOrder : uint8_t { SINGLE_REGISTER, CONFIGURABLE, UNRESOLVED };\n",
              "/** Per-entry source issues; these flags are independent of hardware qualification. */\n",
              "enum class RegisterIssue : uint32_t {\n    NONE = 0,\n"]
    lines += ["    %s = 0x%08Xu,\n" % (name, value) for name, value in data["issues"].items()]
    lines += ["};\n\n"]
    for enum in data["enums"]:
        lines += ["/** %s Source function-PDF pages: %s. */\n" % (enum["notes"] or enum["name"], ", ".join(map(str, enum["pages"]))),
                  "enum class %s : %s {\n" % (enum["name"], enum["underlying"])]
        for value in enum["values"]:
            lines += ["    /** %s */\n" % value["description"], "    %s = %d,\n" % (value["name"], value["value"])]
        lines += ["};\n\n"]
    lines += ["/** Offsets within one documented position segment; index is 1 through 16. */\n",
              "enum class PositionSegmentField : uint8_t { PULSES = 0, SPEED = 2, ACCELERATION_TIME = 3, DECELERATION_TIME = 4, RESERVED = 5 };\n",
              "/** Offsets within one documented speed segment; index is 1 through 16. */\n",
              "enum class SpeedSegmentField : uint8_t { SPEED = 0, ACCELERATION_TIME = 1, DECELERATION_TIME = 2 };\n\n", CLOSE_NS]
    return "".join(lines)


def access_header(data, rows):
    # One byte per address keeps codec access checks independent of the optional
    # string-rich catalogue. Both outputs use this one source ledger.
    flags = [0] * 0x140
    for row in rows:
        if row["signedness"] == "RESERVED":
            continue
        read = row["source_access"] in ("RO", "RW", "RW/S")
        single_write = row["source_access"] in ("WO", "RW", "RW/S") and row["words"] == 1
        for word in range(int(row["address"], 16), int(row["address"], 16) + row["words"]):
            flags[word] = int(read) | (int(single_write) << 1)
    lines = [NOTICE, '#pragma once\n\n#include <stdint.h>\n\n', OPEN_NS,
             'namespace Detail {\n',
             '// bit0: readable; bit1: single-word writable. Zero rejects raw access.\n',
             'constexpr uint8_t ACCESS[] = {\n']
    for start in range(0, len(flags), 16):
        lines.append('    ' + ', '.join(str(flag) for flag in flags[start:start + 16]) +
                     ', // 0x%04X\n' % start)
    lines += ['};\n\n',
              'inline bool canRead(uint16_t address) noexcept {\n',
              '    return address < sizeof(ACCESS) && (ACCESS[address] & 1) != 0;\n}\n\n',
              'inline bool canWriteSingle(uint16_t address) noexcept {\n',
              '    return address < sizeof(ACCESS) && (ACCESS[address] & 2) != 0;\n}\n\n',
              '// Exact source-reviewed FC10 windows; adjacency does not imply permission.\n',
              'inline bool canWriteMultiple(uint16_t start, uint16_t count) noexcept {\n',
              '    return ' + ' ||\n           '.join('(start == 0x%04X && count == %d)' %
                  (int(w['start'], 16), w['count']) for w in data['write_multiple_windows']) + ';\n}\n\n',
              'inline bool hasWriteMultipleCount(uint16_t count) noexcept {\n',
              '    return ' + ' || '.join('count == %d' % count for count in
                  sorted({w['count'] for w in data['write_multiple_windows']})) + ';\n}\n\n',
              '} // namespace Detail\n', CLOSE_NS]
    return ''.join(lines)


def registers_header(rows):
    lines = [NOTICE, "#pragma once\n\n#include <cstddef>\n#include <stdint.h>\n",
              '#include "MotorControlRS/profiles/ess_rs/Types.h"\n\n', OPEN_NS,
              "\n/** Source addresses. HIGH/LOW suffixes are the manual's default-order labels.\n",
              " * Select the active word order before decoding paired fields. No I/O or setters. */\n",
              "namespace Registers {\n"]
    for row in rows:
        address = int(row["address"], 16)
        lines.append("constexpr uint16_t %s = 0x%04X;\n" % (row["name"], address))
        if row["words"] == 2:
            lines.append("constexpr uint16_t %s_HIGH = 0x%04X;\n" % (row["name"], address))
            lines.append("constexpr uint16_t %s_LOW = 0x%04X;\n" % (row["name"], address + 1))
    lines += ["} // namespace Registers\n\n",
              "/** Immutable catalogue metadata, not an operational read/write capability.\n",
              " * All strings have static lifetime. Ranges/defaults are source text, never\n",
              " * executable validation or initialization values. Every word is 16 bits.\n",
              " * sourceAccess retains RW/S without claiming persistence semantics.\n",
              " * No field or entry is hardware-qualified by this catalogue. */\n",
              "struct RegisterDescriptor {\n",
              "    uint16_t address;\n    uint8_t wordCount;\n    RegisterAccess access;\n",
              "    RegisterSignedness signedness;\n    RegisterWordOrder wordOrder;\n",
              "    uint32_t issues;\n    uint8_t sourcePage;\n",
              "    const char* name;\n    const char* unit;\n    const char* sourceRange;\n",
              "    const char* sourceDefault;\n    const char* sourceAccess;\n    const char* notes;\n};\n\n",
              "/** Semantic homing choice; method is not a negative wire encoding. */\n",
              "struct HomingMethodDescriptor {\n    int16_t method;\n    uint8_t firstSourcePage;\n",
              "    bool requiresMotorIndex;\n    bool semanticsUnresolved;\n    const char* notes;\n};\n\n",
              "/** Return the fixed descriptor count; no allocation, state mutation or I/O. */\n",
              "std::size_t registerCount() noexcept;\n",
              "/** Return immutable entry for zero-based index, or nullptr when out of range. */\n",
              "const RegisterDescriptor* registerAt(std::size_t index) noexcept;\n",
              "/** Return the entry containing address, including the second word of a pair.\n",
              " * Unknown holes/outside-map addresses return nullptr. Reserved entries remain\n",
              " * visible with access RESERVED. Bounded search; returned pointer is static. */\n",
              "const RegisterDescriptor* findRegister(uint16_t address) noexcept;\n",
              "/** Source issue test only; this does not establish an operation's support. */\n",
              "bool hasRegisterIssue(const RegisterDescriptor& entry, RegisterIssue issue) noexcept;\n",
              "/** Position segment 1..16; invalid segment/field returns nullptr. No I/O. */\n",
              "const RegisterDescriptor* positionSegmentRegister(uint8_t segment, PositionSegmentField field) noexcept;\n",
              "/** Speed segment 1..16; invalid segment/field returns nullptr. No I/O. */\n",
              "const RegisterDescriptor* speedSegmentRegister(uint8_t segment, SpeedSegmentField field) noexcept;\n",
              "/** Shared PT/PV starting-speed segment 1..16; invalid index returns nullptr. */\n",
              "const RegisterDescriptor* segmentStartSpeedRegister(uint8_t segment) noexcept;\n",
              "/** X terminal 0..3; invalid terminal returns nullptr. */\n",
              "const RegisterDescriptor* inputFunctionRegister(uint8_t terminal) noexcept;\n",
              "/** Y terminal 0..1; invalid terminal returns nullptr. */\n",
              "const RegisterDescriptor* outputFunctionRegister(uint8_t terminal) noexcept;\n",
              "/** Fixed count of listed semantic homing choices, including unresolved negatives. */\n",
              "std::size_t homingMethodCount() noexcept;\n",
              "/** Listed choice or nullptr; lookup is not approval to encode or execute it. */\n",
              "const HomingMethodDescriptor* findHomingMethod(int16_t method) noexcept;\n\n", CLOSE_NS]
    return "".join(lines)


def source_file(data, rows):
    lines = [NOTICE, '#include "MotorControlRS/profiles/ess_rs/Registers.h"\n\n', OPEN_NS,
              "namespace {\nconst RegisterDescriptor CATALOGUE[] = {\n"]
    accesses = {"RO": "READ_ONLY", "WO": "WRITE_ONLY", "RW": "READ_WRITE", "RW/S": "READ_WRITE", "UNSPECIFIED": "UNSPECIFIED"}
    for row in rows:
        access = "RESERVED" if row["signedness"] == "RESERVED" else accesses[row["source_access"]]
        mask = sum(data["issues"][issue] for issue in set(row["issues"]))
        lines += ["    // Function PDF pages %s.\n" % ", ".join(map(str, row["pages"])),
                  "    {0x%04X, %d, RegisterAccess::%s, RegisterSignedness::%s,\n" % (int(row["address"], 16), row["words"], access, row["signedness"]),
                  "     RegisterWordOrder::%s, 0x%08Xu, %d,\n" % (row["word_order"], mask, row["pages"][0]),
                  "     %s, %s,\n" % (quoted(row["name"]), quoted(row["unit"])),
                  "     %s, %s, %s,\n" % (quoted(row["source_range"]), quoted(row["source_default"]), quoted(row["source_access"])),
                  "     %s},\n" % quoted(row["notes"])]
    lines += ["};\n\nconst HomingMethodDescriptor HOMING_METHODS[] = {\n"]
    modes = next(e for e in data["enums"] if e["name"] == "HomingMethod")["values"]
    for mode in modes:
        n = mode["value"]
        lines.append("    {%d, %d, %s, %s, %s},\n" % (n, mode["pages"][0], str(1 <= n <= 14 or n in (33, 34)).lower(), str(n < 0 or n == 18).lower(), quoted(mode["description"])))
    lines += ["};\n} // namespace\n\n", """std::size_t registerCount() noexcept {
    return sizeof(CATALOGUE) / sizeof(CATALOGUE[0]);
}

const RegisterDescriptor* registerAt(std::size_t index) noexcept {
    return index < registerCount() ? &CATALOGUE[index] : nullptr;
}

const RegisterDescriptor* findRegister(uint16_t address) noexcept {
    std::size_t first = 0;
    std::size_t last = registerCount();
    while (first < last) {
        const std::size_t middle = first + (last - first) / 2;
        const RegisterDescriptor& entry = CATALOGUE[middle];
        if (address < entry.address) {
            last = middle;
        } else if (static_cast<uint32_t>(address) >= static_cast<uint32_t>(entry.address) + entry.wordCount) {
            first = middle + 1;
        } else {
            return &entry;
        }
    }
    return nullptr;
}

bool hasRegisterIssue(const RegisterDescriptor& entry, RegisterIssue issue) noexcept {
    const uint32_t mask = static_cast<uint32_t>(issue);
    return mask != 0 && (entry.issues & mask) == mask;
}

const RegisterDescriptor* positionSegmentRegister(uint8_t segment, PositionSegmentField field) noexcept {
    if (segment < 1 || segment > 16) return nullptr;
    const uint8_t offset = static_cast<uint8_t>(field);
    if (offset != 0 && offset != 2 && offset != 3 && offset != 4 && offset != 5) return nullptr;
    return findRegister(static_cast<uint16_t>(Registers::POSITION_SEGMENT_01_PULSES + (segment - 1) * 6 + offset));
}

const RegisterDescriptor* speedSegmentRegister(uint8_t segment, SpeedSegmentField field) noexcept {
    if (segment < 1 || segment > 16) return nullptr;
    const uint8_t offset = static_cast<uint8_t>(field);
    if (offset > 2) return nullptr;
    return findRegister(static_cast<uint16_t>(Registers::SPEED_SEGMENT_01_SPEED + (segment - 1) * 3 + offset));
}

const RegisterDescriptor* segmentStartSpeedRegister(uint8_t segment) noexcept {
    if (segment < 1 || segment > 16) return nullptr;
    return findRegister(static_cast<uint16_t>(Registers::SEGMENT_START_SPEED_01_VALUE + segment - 1));
}

const RegisterDescriptor* inputFunctionRegister(uint8_t terminal) noexcept {
    return terminal < 4 ? findRegister(static_cast<uint16_t>(Registers::INPUT_X0_FUNCTION + terminal)) : nullptr;
}

const RegisterDescriptor* outputFunctionRegister(uint8_t terminal) noexcept {
    return terminal < 2 ? findRegister(static_cast<uint16_t>(Registers::OUTPUT_Y0_FUNCTION + terminal)) : nullptr;
}

std::size_t homingMethodCount() noexcept {
    return sizeof(HOMING_METHODS) / sizeof(HOMING_METHODS[0]);
}

const HomingMethodDescriptor* findHomingMethod(int16_t method) noexcept {
    for (std::size_t i = 0; i < homingMethodCount(); ++i) {
        if (HOMING_METHODS[i].method == method) return &HOMING_METHODS[i];
    }
    return nullptr;
}

""", CLOSE_NS]
    return "".join(lines)


def markdown(data, rows, occupied):
    lines = ["# ESS-RS source register catalogue\n\n",
             "Generated from [ess_rs_registers.json](ess_rs_registers.json) by\n",
             "[generate_ess_registers.py](../../scripts/generate_ess_registers.py).\n",
             "Edit the ledger and regenerate; `--check` detects drift.\n\n",
             "This catalogues the full ESS-RS appendix and named command choices. It\n",
             "implements immutable metadata and bounded lookup only: no frame codec,\n",
             "setter, motion preparation, transport, CLI or hardware support is implied.\n",
             "The [profile contract](../profile_contract.md) remains the operational\n",
             "coverage contract; source completeness is not operational completeness.\n\n",
             "## Evidence and counts\n\n",
             "The original [function PDF](../vendor/Modbus-Series-Bus-Product-Function-Manual-V1.0_1_.pdf)\n",
             "physical pages 68-79 supply the ESS map; pages 13-30 and 32-67 were also\n",
             "visually reviewed for commands, I/O, paired words and homing diagrams.\n",
             "DM-PR pages 80-90 are excluded. The [hardware PDF](../vendor/ESS23-RS1020_Series_Bus_Integrated_Motor_Hardware_Manual.pdf)\n",
             "pages 3, 8, 11 and 12 establish model scope, terminals, DIP differences\n",
             "and alarm labels. Exact hashes and page evidence are in the ledger.\n\n",
             "- %d logical descriptors covering %d distinct 16-bit register words.\n" % (len(rows), len(occupied)),
             "- 21 paired records: five ordinary pairs and sixteen position-segment pairs.\n",
             "- Sixteen stored position segments, sixteen speed segments, sixteen shared start speeds.\n",
             "- Sixteen explicitly reserved position-segment words retained as reserved metadata.\n",
             "- %d typed choice/bitfield groups with %d named values, including 35 homing methods.\n\n" % (len(data["enums"]), sum(len(e["values"]) for e in data["enums"])),
             "Every descriptor and returned string has static lifetime. `findRegister`\n",
             "returns the containing logical record for either word of a pair; an\n",
             "undocumented address returns null. Indexed helpers accept segments 1-16,\n",
             "inputs X0-X3 and outputs Y0-Y1, and reject invalid indexes/field values.\n",
             "HIGH/LOW constants use the manual's default-order labels; active word\n",
             "order still must be established. No pointer or configuration is retained.\n\n",
             "## Limits on interpretation\n\n"]
    lines += ["- " + note + "\n" for note in data["global_notes"]]
    lines += ["- Four ESS inputs do not establish externally selectable sixteen-segment operation:\n",
              "  pages 23-24 note a maximum of eight selected segments for four-input devices.\n",
              "  The sixteen stored register sets are still fully catalogued.\n",
              "- Position and speed segment execution requires external inputs; no serial segment-start command is invented.\n",
              "- Negative homing modes are semantic IDs only. Their wire encoding and paths remain unresolved.\n",
              "- The homing-offset pair is omitted from the page 30 configurable-word-order list; applicability stays unresolved.\n",
              "- Source inconsistencies remain per-entry issue flags and notes; an empty issue mask is not hardware qualification.\n\n",
              "## Register inventory\n\n",
              "Ranges, units and defaults below are source metadata. Parenthesized\n",
              "inconsistencies are retained; they are not silently converted to scaling.\n",
              "RW/S is the vendor notation, with persistence/application unresolved.\n\n",
              "| Address | Name | Words | Source access | Native unit | Source range | Source default | PDF pages | Issues |\n",
              "| --- | --- | ---: | --- | --- | --- | --- | --- | --- |\n"]
    for row in rows:
        lines.append("| `%s` | `%s` | %d | %s | %s | %s | %s | %s | %s |\n" % (row["address"], row["name"], row["words"], "RESERVED (source " + row["source_access"] + ")" if row["signedness"] == "RESERVED" else row["source_access"], row["unit"], row["source_range"], row["source_default"], ", ".join(map(str, row["pages"])), ", ".join(row["issues"]) or "none recorded"))
    lines += ["\n## Reviewed FC10 windows and writable pairs\n\n",
              "Only these complete transactions are admitted. Counts are not a device-wide\n",
              "maximum; subsets and adjacent fields gain no permission. FC06 rejects every\n",
              "paired half. Atomicity and partial-application behavior remain unspecified.\n",
              "See the [pair-write handoff](../ess_pair_writes.md) for typed availability\n",
              "and the gated qualification experiment.\n\n",
              "| Start | Count | Physical PDF pages | Evidence |\n| --- | ---: | --- | --- |\n"]
    for window in data["write_multiple_windows"]:
        lines.append("| `%s` | %d | %s | %s |\n" % (window["start"], window["count"],
                     ", ".join(map(str, window["pages"])), window["evidence"]))
    lines += ["\n| Writable pair | First word | Source disposition |\n| --- | --- | --- |\n"]
    for row in rows:
        if "write_constraint" in row:
            lines.append("| `%s` | `%s` | %s |\n" % (row["name"], row["address"], row["write_constraint"]))
    lines += ["\n## Undocumented address holes\n\n",
              "Within the appendix span 0x0000-0x013F, the following holes have no ESS\n",
              "entry. They are not declared readable, writable or reserved by inference.\n\n"]
    coverage = data["address_coverage"]
    lines += ["%d undocumented words in %d intervals, separately audited against the\n" %
              (coverage["gap_words"], len(coverage["gaps"])),
              "appendix. These are distinct from 16 explicitly reserved words and\n",
              "the documented 0x003B/0x003C entries with unspecified access.\n\n",
              "| First | Last | PDF pages | Evidence |\n| --- | --- | --- | --- |\n"]
    for gap in coverage["gaps"]:
        lines.append("| `%s` | `%s` | %s | %s |\n" %
                     (gap["first"], gap["last"], ", ".join(map(str, gap["pages"])), gap["notes"]))
    lines += ["\nThe generator requires documented words and audited gaps to cover the\n",
              "entire 0x0000-0x013F span without overlap. Its private 320-byte access\n",
              "map lets the codec reject gaps without linking catalogue descriptions.\n"]
    lines += ["\nGeneric references outside the ESS map:\n\n"]
    lines += ["- `%s` (pages %s): %s\n" % (r["addresses"], ", ".join(map(str, r["pages"])), r["reason"]) for r in data["outside_map_references"]]
    lines += ["\n## Named values and bitfields\n\n",
              "Bit enums contain masks; other enums contain semantic native choices.\n",
              "These declarations do not validate arbitrary bit combinations or implement\n",
              "operations. Preserve unknown raw values rather than inventing enum labels.\n\n"]
    for enum in data["enums"]:
        lines += ["### `%s`\n\n" % enum["name"], (enum["notes"] + "\n\n") if enum["notes"] else "",
                  "| Name | Value | Meaning | Function PDF pages |\n| --- | ---: | --- | --- |\n"]
        lines += ["| `%s` | %d | %s | %s |\n" % (v["name"], v["value"], v["description"], ", ".join(map(str, v["pages"]))) for v in enum["values"]]
        lines.append("\n")
    lines += ["## Verification boundary\n\n",
              "The native catalogue tests check address coverage, access separation,\n",
              "paired lookup, indexed bounds, selected independent manual values,\n",
              "homing gaps and unresolved metadata. Generator checking prevents stale\n",
              "code/doc tables. These are software/source checks, not protocol,\n",
              "persistence, physical motion or stopping qualification.\n"]
    return "".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads(LEDGER.read_text(encoding="utf-8"))
    rows = expand(data)
    occupied = validate(data, rows)
    outputs = {
        PUBLIC / "Types.h": types_header(data),
        PUBLIC / "Registers.h": registers_header(rows),
        ROOT / "src/profiles/ess_rs/Registers.cpp": source_file(data, rows),
        ROOT / "src/profiles/ess_rs/Access.h": access_header(data, rows),
        ROOT / "docs/reference/05_ess_register_catalog.md": markdown(data, rows, occupied),
    }
    stale = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print("Stale ESS catalogue output: " + ", ".join(stale), file=sys.stderr)
        return 1
    print("ESS catalogue %s: %d descriptors, %d words" % ("checked" if args.check else "generated", len(rows), len(occupied)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
